### ISSUE TITLE
Cron Stops running with 9.0.1 RC1

### ISSUE THREAD

**Issue by bboule** [owncloud/files_antivirus#103]
Steps to reproduce

Upgrade from OC 9.0.1 Beta to OC 9.0.1 RC1
Cron stops running 3.
Expected behaviour

Cron should continue to run

Actual behaviour

When Cron.php attempts to run we see this:
PHP Fatal error: Cannot make non static method OC\BackgroundJob\Job::run() static in class OCA\Files_Antivirus\Cron\Task in /var/www/html/owncloud/apps/files_antivirus/lib/cron/task.php on line 15

Server configuration

Operating system: CentOS7

Web server:Apache

Database:MySQL

PHP version: 5.6

ownCloud version: 9.0.1 RC1
**Updated from an older ownCloud or fresh install: Update from 9.0.1 Beta

**Where did you install ownCloud from: TAR

**Comment by bboule** [comment]
@cmonteroluque @MTRichards

**Comment by RealRancor** [comment]
Sorry, have missed https://github.com/owncloud/files_antivirus/pull/102 when pointing you here. Not quite sure if this is already fixed there? @VicDeo might be able to tell.

**Comment by MTRichards** [comment]
@cmonteroluque Need to get this working for 9.0.1.
@VicDeo 

Making it a sev 1 since we can't ship with this broken.

@felixboehm FYI

**Comment by VicDeo** [comment]
@bboule does https://github.com/owncloud/files_antivirus/pull/104 help?

**Comment by bboule** [comment]
That fixed it!!!!

**Comment by cmonteroluque** [comment]
@VicDeo thanks

**Comment by VicDeo** [comment]
@cmonteroluque yes, fixed a week ago
