### ISSUE TITLE
Buttons "Add rule" does nothing, neither does "Advanced"

### ISSUE THREAD

**Issue by crysman** [owncloud/files_antivirus#108]
I wanted to try what "add rules" does - but the button does not anything after clicking on it... any hints?

using "czech" language

owncloud: ownCloud 8.2.3 (stable)
app: Antivirus App for files 0.8.0.1
php 5.5.30

**Comment by VicDeo** [comment]
@crysman Does it work with English interface?

**Comment by crysman** [comment]
@VicDeo Yes, it neither works when I set the UI to English.

And more concerning is that the same problem is here https://github.com/owncloud/files_antivirus/issues/107

**Comment by crysman** [comment]
We've just upgraded to OC 9.1.2 (stable), issue still persists.
PHP 5.6.27
Apache/2.4.10
