### ISSUE TITLE
Antivirus can't scan file because file not found

### ISSUE THREAD

**Issue by JochenHWezel** [owncloud/files_antivirus#114]
I get continueously following error in my owncloud log:

`Error while running background job (class: OC\BackgroundJob\Legacy\RegularJob, arguments: Array ( [0] => OCA\Files_Antivirus\Cron\Task [1] => run ) ): {"Exception":"OCP\\Files\\NotFoundException","Message":"File with id \"8\" has not been found.","Code":0,"Trace":"#0 \/var\/www\/owncloud\/apps\/files_antivirus\/lib\/backgroundscanner.php(78): OC\\Files\\View->getPath(8)\n#1 \/var\/www\/owncloud\/apps\/files_antivirus\/lib\/cron\/task.php(21): OCA\\Files_Antivirus\\BackgroundScanner->run()\n#2 [internal function]: OCA\\Files_Antivirus\\Cron\\Task::run()\n#3 \/var\/www\/owncloud\/lib\/private\/backgroundjob\/legacy\/regularjob.php(31): call_user_func(Array)\n#4 \/var\/www\/owncloud\/lib\/private\/backgroundjob\/job.php(52): OC\\BackgroundJob\\Legacy\\RegularJob->run(Array)\n#5 \/var\/www\/owncloud\/cron.php(145): OC\\BackgroundJob\\Job->execute(Object(OC\\BackgroundJob\\JobList), Object(OC\\Log))\n#6 {main}","File":"\/var\/www\/owncloud\/lib\/private\/files\/view.php","Line":1643}`

The file should be ignored if it can't be found any more (I assume it was one of the very first sample files when I installed owncloud, immediately after basic installation I moved the data directory to another location by changing the config.php (but not moved the previous owncloud data directory - I just started with a fresh, empty data directory).

Since it's in my case a sample file and in cases of other users it might be some other reasons, the log isn't worth to be filled up every few minutes with the same warning. Just detect it once, write it to the log, then drop the file from the files-to-scan-todo-list! :-)

**Comment by JochenHWezel** [comment]
OPTIONAL/SUGGESTED: In case that some references to files exist in owncloud database, but the files in the data directory have been removed, there should be an auto-cleanup of the database to drop all those invalid file entries. This would include those file entries in the to-scan list of the antivirus module.

**Comment by lahmizzar** [comment]
+1

**Comment by VicDeo** [comment]
Fixed with
Stable9 https://github.com/owncloud/files_antivirus/pull/128
Stable9.1 https://github.com/owncloud/files_antivirus/pull/127
master https://github.com/owncloud/files_antivirus/pull/118
