### ISSUE TITLE
Function "delete Files" not work

### ISSUE THREAD

**Issue by Dubi01** [owncloud/files_antivirus#116]
Hello
when I activate the funktion "delete Files" then I get the following Error Message in my Log and the file is not deleted.
When im logged in into the Database and search for the File with ID 209, it gives me out a folder who exist.
Does anyone have an Idea?
Thanks :)

Debian 7 x64
MySQL 5.5
PHP 5.6
Apache 2.4.10

Exception: {"Exception":"OCP\\Files\\NotFoundException","Message":"File with id \"209\" has not been found.","Code":0,"Trace":"
#0 \/storage\/htdocs\/owncloud\/apps\/files_sharing\/lib\/sharedstorage.php(90): OC\\Files\\View->getPath(209)\n
#1 \/storage\/htdocs\/owncloud\/apps\/files_sharing\/lib\/sharedstorage.php(581): OC\\Files\\Storage\\Shared->init()\n
#2 \/storage\/htdocs\/owncloud\/lib\/private\/files\/storage\/wrapper\/wrapper.php(381): OC\\Files\\Storage\\Shared->getCache('', Object(OCA\\Files_Antivirus\\AvirWrapper))\n
#3 \/storage\/htdocs\/owncloud\/lib\/private\/files\/storage\/wrapper\/wrapper.php(381): OC\\Files\\Storage\\Wrapper\\Wrapper->getCache('', Object(OCA\\Files_Antivirus\\AvirWrapper))\n
#4 \/storage\/htdocs\/owncloud\/lib\/private\/files\/cache\/scanner.php(88): OC\\Files\\Storage\\Wrapper\\Wrapper->getCache()\n
#5 \/storage\/htdocs\/owncloud\/apps\/files_sharing\/lib\/sharedstorage.php(595): OC\\Files\\Cache\\Scanner->__construct(Object(OCA\\Files_Antivirus\\AvirWrapper))\n
#6 \/storage\/htdocs\/owncloud\/lib\/private\/files\/storage\/wrapper\/wrapper.php(395): OC\\Files\\Storage\\Shared->getScanner('', Object(OCA\\Files_Antivirus\\AvirWrapper))\n
#7 \/storage\/htdocs\/owncloud\/lib\/private\/files\/storage\/wrapper\/wrapper.php(395): OC\\Files\\Storage\\Wrapper\\Wrapper->getScanner('', Object(OCA\\Files_Antivirus\\AvirWrapper))\n
#8 \/storage\/htdocs\/owncloud\/lib\/private\/files\/utils\/scanner.php(127): OC\\Files\\Storage\\Wrapper\\Wrapper->getScanner()\n
#9 \/storage\/htdocs\/owncloud\/apps\/files\/lib\/backgroundjob\/scanfiles.php(87): OC\\Files\\Utils\\Scanner->backgroundScan('')\n
#10 \/storage\/htdocs\/owncloud\/apps\/files\/lib\/backgroundjob\/scanfiles.php(111): OCA\\Files\\BackgroundJob\\ScanFiles->runScanner(Object(OC\\User\\User))\n
#11 \/storage\/htdocs\/owncloud\/lib\/private\/backgroundjob\/job.php(52): OCA\\Files\\BackgroundJob\\ScanFiles->run(NULL)\n
#12 \/storage\/htdocs\/owncloud\/lib\/private\/backgroundjob\/timedjob.php(53): OC\\BackgroundJob\\Job->execute(Object(OC\\BackgroundJob\\JobList), Object(OC\\Log))\n
#13 \/storage\/htdocs\/owncloud\/cron.php(171): OC\\BackgroundJob\\TimedJob->execute(Object(OC\\BackgroundJob\\JobList), Object(OC\\Log))\n
#14 {main}","File":"\/storage\/htdocs\/owncloud\/lib\/private\/files\/view.php","Line":1677}

**Comment by VicDeo** [comment]
@Dubi01 this is a known issue
It is already tracked in  https://github.com/owncloud/files_antivirus/issues/109 
Closing as a duplicate
