### ISSUE TITLE
No notification email when trying to upload infected file via client

### ISSUE THREAD

**Issue by jerrac** [owncloud/files_antivirus#12]
I tried placing a file like what is described here: http://www.computerhope.com/issues/ch001386.htm in my OwnCloud folder. OwnCloud did not upload the file, but it did not actually send an email notifying me that my file was infected.

```syslog
Jan 21 11:17:25 ws-prod-filehost-01 ownCloud[22621]: {files_antivirus} Exec scan: /trytwo.exe
Jan 21 11:17:25 ws-prod-filehost-01 ownCloud[22621]: {files_antivirus} Virus(es) found: Eicar-Test-Signature
Jan 21 11:17:26 ws-prod-filehost-01 ownCloud[22621]: {files_antivirus} Email: me@blah.tld
```

I assume that last line indicates that OwnCloud tried to send an email...

Here are a few more log messages that might be applicable.

```syslog
Jan 21 11:17:26 ws-prod-filehost-01 ownCloud[22621]: {hook} error while running hook (\OCA\Files_Antivirus\Scanner::av_scan): Session has been closed - no further changes to the session as allowed
Jan 21 11:17:26 ws-prod-filehost-01 ownCloud[22621]: {sharing} No fileinfo available for: /trytwo.exe
Jan 21 11:17:26 ws-prod-filehost-01 ownCloud[22621]: {webdav} Sabre\DAV\Exception: Could not rename part file to final file
Jan 21 11:17:26 ws-prod-filehost-01 ownCloud[22621]: {webdav} \OC\Files\Filesystem::rename() failed
```

I have php logging to syslog as well, and I saw no php errors in the timeperiod I was trying to upload the trytwo.exe file. Nor were there any postfix messages about sending any email. Which means owncloud did not succeed in sending an email, if it even really tried.

For my server, I'm running ownCloud 7.0.4 (stable) on Ubuntu 12.04.5 LTS 64bit.

Client is 1.7.7 on Ubuntu 14.04 64bit.

Note, if I try uploading the file via the webui, the ui notifies the user that they tried to upload an infected file, and OwnCloud succeeds in sending a notification email as well. So, this issue is definitely client specific.

**Comment by karlitschek** [comment]
@VicDeo any idea?

**Comment by jerrac** [comment]
FYI, my first tests were on 242b586f7e86ea3a9dcfa6f4dc33a2006f18a153 of files_antivirus. And I just pulled master and tested again with the same results.

**Comment by jerrac** [comment]
And I just noticed that the client is throwing errors like:

Error downloading https://filehost.lanecc.edu/remote.php/webdav/ecairtest.exe - server replied: Internal Server Error (Could not rename part file to final file)

Which is a really really weird error message since the server doesn't even have that file on it...

**Comment by DeepDiver1975** [comment]
> Which is a really really weird error message since the server doesn't even have that file on it...

we are looking out for alternative integration points for future versions of ownCloud - see https://github.com/owncloud/core/issues/12052#issuecomment-63969264

**Comment by DeepDiver1975** [comment]
> Jan 21 11:17:26 ws-prod-filehost-01 ownCloud[22621]: {hook} error while running hook (\OCA\Files_Antivirus\Scanner::av_scan): Session has been closed - no further changes to the session as allowed

@VicDeo I assume this is the root cause why the email is not sent - please have a look - thx

**Comment by DeepDiver1975** [comment]
well - according to the code the email is sent to the logged in user in case an email is specified: https://github.com/owncloud/files_antivirus/blob/master/lib/notification.php#L16

I'm wondering if this is that sensful - the logged in user already does get feedback via the canceled upload.

**Comment by jerrac** [comment]
@DeepDiver1975 A) This issue is about what happens with the sync client, not the web ui. B) We do want the email. The notification in the web ui is only shown briefly, and it wouldn't surprise me if users never notice it. Maybe if the notification was something the user actually had to read and dismiss themselves... But I'd bet some would still just not get it. An email adds another level of confirmation.

**Comment by VicDeo** [comment]
@jerrac Can you test  https://github.com/owncloud/files_antivirus/pull/16 ?

**Comment by DeepDiver1975** [comment]
> A) This issue is about what happens with the sync client, not the web ui.

a canceled upload shall also be reported on the client - which is not the case - see #15 

Regarding the receiver of the email - I would have expected that the admin(s) get some notification.

@VicDeo regarding notification - please get in touch with @nickvergessen to integrate files_antivirus with the activity app.

**Comment by VicDeo** [comment]
@jerrac can you retest with recent master or stable8?

**Comment by VicDeo** [comment]
oh, wait, it hasn't fixed yet.

**Comment by VicDeo** [comment]
>Regarding the receiver of the email - I would have expected that the admin(s) get some notification.

@DeepDiver1975 
which admin? Any admin user, all admin users or I need to introduce a new field for recipient?
