### ISSUE TITLE
fwrite(): send of 1028 bytes failed with errno=32 Broken pipe at ....

### ISSUE THREAD

**Issue by alphamat** [owncloud/files_antivirus#124]
I use cloud server 9 with debian 8 & php 7, apache 2.4, antivirus app daemon socket - also in use latest branche from here - i have in log a lot of this error messages:

`fwrite(): send of 4 bytes failed with errno=32 Broken pipe at /var/www/virtual/htdocs/apps/files_antivirus/lib/scanner/external.php#51

fwrite(): send of 931 bytes failed with errno=32 Broken pipe at /var/www/virtual/htdocs/apps/files_antivirus/lib/scanner.php#68

fwrite(): send of 1028 bytes failed with errno=32 Broken pipe at /var/www/virtual/htdocs/apps/files_antivirus/lib/scanner.php#68`

install & activation of the app was without any problem - i hope somebody can help with this issue

thx

**Comment by Bliepo2** [comment]
To me this seems to be a bug. I have the exact same issue on my ownCloud, with ownCloud server 9.1, Debian Jessie. I also found similair reports at https://www.bountysource.com/issues/36929179-antivirus-data-stream-problem-fills-log-file.

**Comment by Basseuph** [comment]
We face the same issue since the last update of owncloud and now deactivated virus scanning, which definitely is not the nice way of handling this. We run owncloud 9.1 (9.1.1-1.1 from owncloud repo) on Debian Jessie 8.6.

**Comment by e-alfred** [comment]
Maybe related to this one?

https://github.com/owncloud/files_antivirus/issues/110

**Comment by Bliepo2** [comment]
No, I don't think they are related. The only error I have is this one:
"Error 	PHP 	fwrite(): send of 4 bytes failed with errno=32 Broken pipe at /var/www/owncloud/apps/files_antivirus/lib/scanner/external.php#51 	2016-09-29T22:15:04+00:00
Error	PHP	fwrite(): send of 4 bytes failed with errno=32 Broken pipe at /var/www/owncloud/apps/files_antivirus/lib/scanner/external.php#51	2016-09-29T07:30:03+00:00
Error	PHP	fwrite(): send of 4 bytes failed with errno=32 Broken pipe at /var/www/owncloud/apps/files_antivirus/lib/scanner/external.php#51	2016-09-29T06:00:04+00:00
Error	PHP	fwrite(): send of 4 bytes failed with errno=32 Broken pipe at /var/www/owncloud/apps/files_antivirus/lib/scanner/external.php#51	2016-09-29T05:00:04+00:00
Error	PHP	fwrite(): send of 4 bytes failed with errno=32 Broken pipe at /var/www/owncloud/apps/files_antivirus/lib/scanner/external.php#51	2016-09-28T03:00:04+00:00"

There is nothing about a file not being found or the like, so I think these are different issues.

**Comment by sidey79** [comment]
Broken pipe at  means that clamav closed the socket. This occures alway, when maxstreamlength is reached.

The antivirus app is currently not checking the return code of the function fwrite, so it doesn't recognice, that the socket was closed.

**Comment by Koblenz** [comment]
I have the same Problem after Updating to the latest OC Release (Debian 8.1).

These error filled my log file massiv in the past week to 20GB. Disabled the app before my partition runs out of space.

**Comment by VicDeo** [comment]
any volunteers to test https://github.com/owncloud/files_antivirus/pull/133?
