### ISSUE TITLE
"Log only" acts just the same as "Delete"

### ISSUE THREAD

**Issue by FireUponSky** [owncloud/files_antivirus#129]
Hi,

I installed files_antivirus today mostly successfully, however I find that the option "Log only" is not working . With option "Log only", file gets blocked with a message "Virus Eicar-Test-Signature is detected in the file. Upload cannot be completed." so does option "Delete". 

Shouldn't they act differently? I expect that "Log only" gives a warning message, a log info and maybe a confirm button, but not prevent files from uploading.
## My system info is:

Operating System: CentOS 7.1
Web server: Apache 
Database: MySQL
PHP version: 7
ownCloud version: 9.1
Updated from an older ownCloud or fresh install: updated from 8
Antivirus App for files 0.9.0.0 with patch #127 

Thank you very much!

**Comment by michag86** [comment]
I think the file will be blocked always on upload, if it's infected.
The option is only used for the background scanner.

**Comment by VicDeo** [comment]
@FireUponSky @michag86 exactly. This option affects cron job only.
Infected files are always deleted on upload.
