### ISSUE TITLE
ClamAV app cannot be enabled after upgrade from 9.1.0 to 9.1.1 version of the ownCloud

### ISSUE THREAD

**Issue by romiro-spb** [owncloud/files_antivirus#130]
An exception occurred while executing 'CREATE TABLE `oc_files_antivirus` (`fileid` INT UNSIGNED NOT NULL, `check_time` INT UNSIGNED DEFAULT 0 NOT NULL, PRIMARY KEY(`fileid`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB': SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oc_files_antivirus' already exists

**Comment by VicDeo** [comment]
@romiro-spb 
please post result for the following SQL query: `select * from oc_appconfig where appid='files_antivirus' and configkey='installed_version'`

**Comment by romiro-spb** [comment]
mysql> select * from oc_appconfig where appid='files_antivirus' and configkey='installed_version';
Empty set (0.00 sec)
mysql> select * from oc_files_antivirus;
Empty set (0.00 sec)
mysql> show create table oc_files_antivirus;
CREATE TABLE `oc_files_antivirus` (
  `fileid` int(10) unsigned NOT NULL,
  `check_time` int(10) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`fileid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin

**Comment by VicDeo** [comment]
@romiro-spb just as I thought. Tables exist, but there is no info about installed app version in `oc_appconfig`.
You can just drop tables `oc_files_antivirus` and `oc_files_avir_status` (if any)
and reenable the app.

**Comment by drelich** [comment]
Running into a similar issue after a fresh/clean install of OC 9.1.3 on Debian 8. At first I got:

> An exception occurred while executing 'CREATE TABLE `files_antivirus` (`fileid` INT UNSIGNED DEFAULT 0 NOT NULL, `check_time` INT UNSIGNED DEFAULT 0 NOT NULL) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB': SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'files_antivirus' already exists

I removed the table. When I tried to enable the antivirus app again, it throws a different error:

> An exception occurred while executing 'SELECT * FROM `files_avir_status`': SQLSTATE[42S02]: Base table or view not found: 1146 Table 'owncloud.files_avir_status' doesn't exist

Any suggestions?

**Comment by VicDeo** [comment]
@drelich 
- ` DELETE FROM oc_appconfig where appid='files_antivirus';`
- drop  `oc_files_antivirus`;
- drop  `oc_files_avir_status`;
- reenable app

I have no idea how it happens but it should be fixed on master/stable10 as we already use migrations there.

**Comment by VicDeo** [comment]
Closing as resolved. Feel free to reopen if it is still reproducible.
