### ISSUE TITLE
BackgroundScanner not working with Nextcloud 10.0.1

### ISSUE THREAD

**Issue by Querschlag** [owncloud/files_antivirus#136]
The BackgroundScanner keeps spaming the log with these entries:
`Error	files_antivirus	OCA\Files_Antivirus\BackgroundScanner::run, exception: Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.
Error	no app in context	Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.
`
Encryption is disabled and the scanned files have not been shared.
I run the app in Daemon(Socket) mode with the recommended stream length of 10485760

**Comment by RealRancor** [comment]
@Querschlag The nextcloud repository for this app is available at https://github.com/nextcloud/files_antivirus

**Comment by VicDeo** [comment]
Closing due to wrong repo.
