### ISSUE TITLE
BackgroundScanner not scanning on md5'd homes

### ISSUE THREAD

**Issue by PVince81** [owncloud/files_antivirus#137]
I saw that the code filters by 'home::%' storages, this will miss the crappy md5 storage entries as per https://github.com/owncloud/core/wiki/Storage-IDs#random-numberstring

The old workaround was to iterate over all users, but it's expensive.

Since OC 9.0 we have the oc_mounts table which is a cache of known mount points, including the user's homes. This should be used to identify the user's home storages.

`select storage_id from oc_mounts where mount_point='/$userId/'`

@VicDeo

**Comment by VicDeo** [comment]
ss.id LIKE 'home::%' OR ss.id NOT LIKE '%::%'
INNER JOIN oc_mounts AS mnt ON mnt.storage_id = ss.numeric_id AND mnt.mount_point = CONCAT('/', mnt.user_id , '/')

:cactus:

**Comment by VicDeo** [comment]
In addition oc_mounts has an info about the owner. 
Replacing  `BackgroundScanner::getOwner` with
```
\OC::$server->getUserManager()->get( mnt.user_id )
```
 can save some CPU cycles  :green_heart:

**Comment by PVince81** [comment]
> :cactus: 

(let's use emojis as ids to refer to comments :wink:)

No need for the "LIKE" on the storages table.
If you only need the storage numeric id then you don't even need to add the oc_storages table.

`select storage_id from oc_mounts where mnt.mount_point = CONCAT('/', mnt.user_id , '/')`.

Then with the storage_id you can join with oc_filecache on the "storage" column.

**Comment by PVince81** [comment]
In normal setups it is not possible to mount anything else than a home on "/$userId/".
One might be able to hack ownCloud to mount an ext storage there, but then it is also ok to scan that one as the home, if that would ever happen...

**Comment by VicDeo** [comment]
@PVince81 this is nearly impossible with the current quotation:
```
SELECT fc.`fileid` FROM `*PREFIX*filecache` fc LEFT JOIN `*PREFIX*files_antivirus` fa ON fa.`fileid` = fc.`fileid` INNER JOIN `*PREFIX*mounts` mnt ON (fc.`storage` = mnt.`storage_id`) AND (mnt.`mount_point` = '/' || mnt.`user_id || '/'`) WHERE (fc.`mimetype` <> '2') AND ((fa.`fileid` IS NULL) OR (fc.`mtime` > fa.`check_time`)) AND (fc.`path` LIKE 'files/%') AND (fc.`size` <> '0')
```

Concatenation operation is escaped in a manner that everything till the very end of string is considered to be a filed name here:
```
mnt.`mount_point` = '/' || mnt.`user_id || '/'`
```
No wonder, there is no field with the name:
```
mnt.`user_id || '/'`
```

**Comment by VicDeo** [comment]
Not a clean solution, but works:
```
$lastConcat = \OC::$server->getDatabaseConnection()->getDatabasePlatform()->getConcatExpression(
 				' ',
 				$qb->expr()->literal('/')
 			);
...
$qb->expr()->eq('mnt.mount_point', $concat) . $lastConcat
...

**Comment by PVince81** [comment]
How about `CONCAT('/', mnt.user_id, '/')` ? Or does it not work with all databases ?

**Comment by VicDeo** [comment]
@PVince81 it will be escaped as 
```
CONCAT('/', mnt.`user_id, '/')`
```

**Comment by VicDeo** [comment]
@PVince81 `||` is a standard for all DB platforms except MySql
https://evertpot.com/writing-sql-for-postgres-mysql-sqlite/

**Comment by PVince81** [comment]
but it's supposed to be:
```
mnt.`mount_point` = '/' || mnt.`user_id` || '/'
```

What code is escaping this ? Are you using our query builder ? If yes you might want to try using `createFunction()` to avoid crazy escaping.

See here for an example: https://github.com/owncloud/core/pull/26562/files#diff-dd95fcdd436670a1f50782631d011d4cR103

**Comment by VicDeo** [comment]
@PVince81 yes, it goes from OC wrapper for query builder
