### ISSUE TITLE
README.md fails code integrity check

### ISSUE THREAD

**Issue by BornToBeRoot** [owncloud/files_antivirus#146]
This happens after upgrading from 8.2.9 to 9.0.7 to 9.1.3

Seems like there is a hash missing

```
Raw output
==========
Array
(
    [files_antivirus] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [README.md] => Array
                        (
                            [expected] => 
                            [current] => d197f4b4e0a845261162fdc8ad5a500e579c68c9306471558da14eb3474b70889772fd88fea1161be341421c4dba3bbc63c5e85a8378b38a75d76dbdb1e3264a
                        )

                )

        )

)
```

**Comment by ryno83** [comment]
I deleted the files and the problem was resolved

**Comment by DeepDiver1975** [comment]
looks like a packaging issue @VicDeo

**Comment by BornToBeRoot** [comment]
@ryno83 I deleted it too, but it should not be there after an upgrade from the repos.

**Comment by PVince81** [comment]
@VicDeo any update ? Could you reproduce this and confirm this is fixed ?

**Comment by VicDeo** [comment]
@PVince81 
I haven't found `README.md` in zip packages for 8.2.x (checked 8.2.8/8.2.9/8.2.10) and 9.0.x (checked 9.0.4/9.0.5)

**Comment by scorpaanon** [comment]
From what I see is a string/Hash missing

**Comment by VicDeo** [comment]
@BornToBeRoot @ryno83 how did you upgrade?

**Comment by BornToBeRoot** [comment]
With the repos you provide for CentOS 7

**Comment by PVince81** [comment]
@VicDeo what's the next step ?

**Comment by VicDeo** [comment]
@PVince81 IDK, there is no such file in packages. 
Maybe it sneaked from prehistoric versions.

**Comment by PVince81** [comment]
but many people seems to be having it. any quick workaround ?

**Comment by BornToBeRoot** [comment]
@PVince81 this is the workaround `rm README.md -f`

**Comment by PVince81** [comment]
if the problem doesn't appear in recent versions then it's probably not worth investing dev time to add code to work this around, closing
