### ISSUE TITLE
When antivirus plugin deletes a file, owncloud core is not aware of that and issues emerge

### ISSUE THREAD

**Issue by crysman** [owncloud/files_antivirus#147]
Problem: We have got issues with antivirus plugin - when antivirus plugin deletes a file, owncloud core is not aware of that and client synchronization starts to fail. **Affected client is not fully synchronized any more** until the file is manually deleted in web OC GUI.

The problem is that that file should not be there in the first place, because it had been deleted by the antivirus.

Expected behavior:
Antivirus deletes the file. OC engine afterwards performs all the procedures like if the file was deleted via OC GUI. In the event log, there is a record about the delete operation and that the file had been deleted by the antivirus.

Sysinfo:
OC 9.1.2 (stable)
PHP 5.6.27
Apache/2.4.10

**Comment by scorpaanon** [comment]
Odd.

**Comment by scorpaanon** [comment]
when you remove a file it still saves a "copy" Please correct me if I am wrong.

**Comment by VicDeo** [comment]
@crysman is this issue still reproducible for you?

**Comment by crysman** [comment]
why wouldn't be? We are still running the same version of OC - shall I upgrade to ver 10 to check? Or has the antivirus plugin got updated since my post?

**Comment by VicDeo** [comment]
9.1 reached EOL, is it reproducible with OC 10?

If it is still an issue please add the list of enabled apps to your report.

**Comment by crysman** [comment]
No more using OwnCloud, needs to be assigned to somebody else... Good luck!
