### ISSUE TITLE
wrong handling of error case if virus is detected

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/files_antivirus#15]
https://github.com/owncloud/files_antivirus/blob/master/lib/scanner.php#L90

bailing out with json error is soo wrong thinking about non browser access - e.g. webdav

Please evaluate how throwing an exception can also provide better feedback via webdav

@VicDeo

**Comment by DeepDiver1975** [comment]
quick test on cadaver even reports an successfull upload:

```shell
Uploading schema.sql to `/remote.php/webdav/schema.sql':
Progress: [=============================>] 100,0% of 794 bytes succeeded.
dav:/remote.php/webdav/> ls
Listing collection `/remote.php/webdav/': succeeded.
        EVOLVE OC LABv2.pdf              1260022  Jan 23 11:32
dav:/remote.php/webdav/> exit
Connection to `localhost' closed.

**Comment by VicDeo** [comment]
@DeepDiver1975 should I throw it for WebDAV connections only?
throwing the exception causes the ''The target folder has been moved or deleted.'' bubble in Web UI at this point https://github.com/owncloud/core/blob/master/apps/files/lib/app.php#L86

Not really descriptive :/

**Comment by DeepDiver1975** [comment]
Please have a look at the exception which are currently handled by our webdav implementation: https://github.com/owncloud/core/blob/master/lib/private/connector/sabre/file.php#L96

One of them shall be suitable for this case.

The same exception should already properly be processed by the web based upload mechanism.

Please test the behavior or sync client as well as regular webdav clients.

THX a lot

**Comment by VicDeo** [comment]
@DeepDiver1975 
I tried throwing
`\OCP\Files\NotPermittedException` 
`(\OCP\Files\EntityTooLargeException`
`\OCP\Files\InvalidContentException` 
it's all the same


```
> put testvirus.txt ./t.png
Uploading testvirus.txt to `/~deo/oc-tmp/remote.php/webdav/t.png':
Progress: [=============================>] 100.0% of 68 bytes failed:
500 Internal Server Error
```

and owncloud.log

```
{"reqId":"21042169f926b8e9c2dffa4804c37700","remoteAddr":"::1","app":"hook","message":"error while running hook (\\OCA\\Files_Antivirus\\Scanner::av_scan): HERE_IS_THE_MESSAGE_I_THROW","level":3,"time":"2015-02-02T19:06:06+00:00","method":"PUT","url":"\/domain\/remote.php\/webdav\/t.png"}
{"reqId":"21042169f926b8e9c2dffa4804c37700","remoteAddr":"::1","app":"PHP","message":"chmod(): Operation not permitted at \/webroot\/lib\/private\/log\/owncloud.php#85","level":0,"time":"2015-02-02T19:06:06+00:00","method":"PUT","url":"\/domain\/remote.php\/webdav\/t.png"}
{"reqId":"21042169f926b8e9c2dffa4804c37700","remoteAddr":"::1","app":"sharing","message":"No fileinfo available for: \/t.png","level":2,"time":"2015-02-02T19:06:06+00:00","method":"PUT","url":"\/domain\/remote.php\/webdav\/t.png"}
{"reqId":"21042169f926b8e9c2dffa4804c37700","remoteAddr":"::1","app":"PHP","message":"chmod(): Operation not permitted at \/webroot\/lib\/private\/log\/owncloud.php#85","level":0,"time":"2015-02-02T19:06:06+00:00","method":"PUT","url":"\/domain\/remote.php\/webdav\/t.png"}
{"reqId":"21042169f926b8e9c2dffa4804c37700","remoteAddr":"::1","app":"webdav","message":"\\OC\\Files\\Filesystem::rename() failed","level":3,"time":"2015-02-02T19:06:06+00:00","method":"PUT","url":"\/domain\/remote.php\/webdav\/t.png"}
{"reqId":"21042169f926b8e9c2dffa4804c37700","remoteAddr":"::1","app":"PHP","message":"chmod(): Operation not permitted at \/webroot\/lib\/private\/log\/owncloud.php#85","level":0,"time":"2015-02-02T19:06:06+00:00","method":"PUT","url":"\/domain\/remote.php\/webdav\/t.png"}
{"reqId":"21042169f926b8e9c2dffa4804c37700","remoteAddr":"::1","app":"webdav","message":"Exception: {\"Message\":\"Could not rename part file to final file\",\"Code\":0,\"Trace\":\"#0 \\\/webroot\\\/lib\\\/private\\\/connector\\\/sabre\\\/directory.php(84): OC_Connector_Sabre_File->put(Resource id #328)\\n#1 \\\/webroot\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(1647): OC_Connector_Sabre_Directory->createFile('t.png', Resource id #328)\\n#2 \\\/webroot\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(900): Sabre\\\\DAV\\\\Server->createFile('t.png', Resource id #328, NULL)\\n#3 [internal function]: Sabre\\\\DAV\\\\Server->httpPut('t.png')\\n#4 \\\/webroot\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(474): call_user_func(Array, 't.png')\\n#5 \\\/webroot\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(214): Sabre\\\\DAV\\\\Server->invokeMethod('PUT', 't.png')\\n#6 \\\/webroot\\\/apps\\\/files\\\/appinfo\\\/remote.php(61): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/webroot\\\/remote.php(54): require_once('\\\/home\\\/deo\\\/publi...')\\n#8 {main}\",\"File\":\"\\\/webroot\\\/lib\\\/private\\\/connector\\\/sabre\\\/file.php\",\"Line\":142}","level":4,"time":"2015-02-02T19:06:06+00:00","method":"PUT","url":"\/domain\/remote.php\/webdav\/t.png"}
{"reqId":"21042169f926b8e9c2dffa4804c37700","remoteAddr":"::1","app":"PHP","message":"chmod(): Operation not permitted at \/webroot\/lib\/private\/log\/owncloud.php#85","level":0,"time":"2015-02-02T19:06:06+00:00","method":"PUT","url":"\/domain\/remote.php\/webdav\/t.png"}
{"reqId":"21042169f926b8e9c2dffa4804c37700","remoteAddr":"::1","app":"PHP","message":"chmod(): Operation not permitted at \/webroot\/lib\/private\/log\/owncloud.php#85","level":3,"time":"2015-02-02T19:06:06+00:00","method":"PUT","url":"\/domain\/remote.php\/webdav\/t.png"}
```

Is it OK to response with 500?

**Comment by VicDeo** [comment]
And  Web UI says `The target folder has been moved or deleted` for infected files regardless the exception class

**Comment by DeepDiver1975** [comment]
Ah - yes - well - this is because antivirus is executed within a hook and hooks only log exceptions.

Hmmm - not much we can for now I guess.

Best would be to move av off the hooks and use a storage wrapper? @icewind1991 
(Is storage wrapper the solution to everything .. this makes me shiver )

**Comment by icewind1991** [comment]
A storage wrapper would make this work yes

**Comment by DeepDiver1975** [comment]
@VicDeo let me know if you need more input on this - @icewind1991 can for sure help out as well.

Let's schedule this for 8.1 - THX

**Comment by DeepDiver1975** [comment]
@VicDeo please take the opportunity while working on this to
- use AppFramework
- push unit test coverage

THX

**Comment by DeepDiver1975** [comment]
@icewind1991 are we already in a stage where we could setup files_antivirus as a mount option?

**Comment by cdamken** [comment]
### Expected behavior
Use sync-client to upload a file with virus and receive an error message that the file contains a virus.

### Actual behavior
Use sync-client to upload a file with virus and client shows a generic server error and not a specific message about infection. 

### Steps to reproduce.
1 Copy a file to the sync folder
2 Wait :smiley: 

@MorrisJobke  There is no Blue-Ticket-Label

00002565

**Comment by DeepDiver1975** [comment]
@cdamken we are working on this - scheduled for 8.1. I highly doubt we can find a proper solution for 8.0EE

**Comment by cdamken** [comment]
@DeepDiver1975 Thanks a lot! :+1:
