### ISSUE TITLE
App does not work with home encryption enabled

### ISSUE THREAD

**Issue by Bobselp** [owncloud/files_antivirus#150]
Hello all,

when enabling encryption of the local storage ("home storage"), antivirus doesn't work anymore. From what I understood the files are encrypted using the users password - and without the password there is no way the file could be decrypted for scanning.

Maybe this should be noted somewhere. Not only so Admins know that enabling this module with home storage encryption enabled is pointless and doesn't work at all, but also because the owncloud log gets cluttered with the following messages when the module is enabled nonetheless:

```
{"reqId":"ce9ShF9vSZL7Xsg9mfWZ","remoteAddr":"","app":"no app in context","message":"Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.","level":3,"time":"February 02, 2017 21:23:08","method":"--","url":"--","user":" ***ACCOUNT***"}
{"reqId":"ce9ShF9vSZL7Xsg9mfWZ","remoteAddr":"","app":"files_antivirus","message":"OCA\\Files_Antivirus\\BackgroundScanner::run, exception: Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.","level":3,"time":"February 02, 2017 21:23:08","method":"--","url":"--","user":" ***ACCOUNT***"}
```

For a server with lots of files, this accumulates to gigabytes of log entries. And the cron job with the BackgroundScanner task runs for hours, clogging up the CPU, despite effectively doing nothing but producing error messages.

**Comment by scorpaanon** [comment]
I'll look in to it and get back to you

**Comment by rapITler** [comment]
Hi,

it seems that I have the same issue which also flooding our logfile.

```
{"reqId":"d0gr9v4SjNJO8xa1QoPa","remoteAddr":"","app":"no app in context","message":"Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.","level":3,"time":"2017-04-25T10:17:59+02:00","method":"--","url":"--","user":"xxx","version":"11.0.1.2"}
{"reqId":"d0gr9v4SjNJO8xa1QoPa","remoteAddr":"","app":"files_antivirus","message":"OCA\\Files_Antivirus\\BackgroundScanner::run, exception: Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.","level":3,"time":"2017-04-25T10:17:59+02:00","method":"--","url":"--","user":"xxxx","version":"11.0.1.2"}

```

We also using Encryption and AV. When we upload a test virus the antivirus identifies it successfully. I am not familiar with the process but it seems to me that a background scan afterwards have an issue with the encrypted files.

Can we configure the AV to only scan files while they get uploaded?

Regards

**Comment by andrewjones216** [comment]
+1 to this, I'm using Encryption at the moment and want to also use AV. I'm hoping that the AV scans files uploaded before it encrypts the file at rest. 
Our only other option would be to disable encryption, as making sure viruses can't be propagated through our OwnCloud instance is more important!

**Comment by patrickjahns** [comment]
By design, using encryption and running a background scan is only possible, when using a master-key encryption. (The server needs to be able to decrypt the file to scan the contents).

When user-key encryption is enabled, the server is not able to access the files.
