### ISSUE TITLE
Do a marketplace release

### ISSUE THREAD

**Issue by butonic** [owncloud/files_antivirus#160]
QA
- [ ] create testplan and test cases
- [ ] test and document in testplan

Marketing
- [ ] Check/Update info.xml (summary, description, etc.) @pmaier 
- [ ] Find screenshot, if necessary

Build
- [ ] bump version to ?
- [ ] sign and build tarball
- [ ] upload to marketplace

Docs
Nothing to do

Communication
- Blogpost on .org ? @lefherz

**Comment by VicDeo** [comment]
Makes no sense without https://github.com/owncloud/files_antivirus/pull/159

**Comment by DeepDiver1975** [comment]
> Makes no sense without #159

why not? one can work on two topics in parallel? 😕

**Comment by VicDeo** [comment]
@DeepDiver1975 because https://github.com/owncloud/files_antivirus/pull/159 is a fix. Why should we release an app that is known to have a broken cronjob inside?

**Comment by DeepDiver1975** [comment]
> Why should we release an app that is known to have a broken cronjob inside?

but yo can still prepare the release - right? 
- [ ] Makefile just like all the other apps have
- [ ] make sure the signing key is at your hand
- [ ] test upload the package to marketplace.in.owncloud.com

**Comment by DeepDiver1975** [comment]
please use the makefile we have everywhere - see e.g. gallery or activity ....

**Comment by VicDeo** [comment]
@DeepDiver1975 all is green ^^^

**Comment by DeepDiver1975** [comment]
staging - https://marketplace.int.owncloud.com/apps/files_antivirus

**Comment by felixboehm** [comment]
QA needed here? Any specific topics to test?

**Comment by pmaier1** [comment]
added release checklist topics to the top post

**Comment by felixboehm** [comment]
follow up in #171
