### ISSUE TITLE
oc 10.0.2 error message only "unsupported media type"

### ISSUE THREAD

**Issue by voroyam** [owncloud/files_antivirus#163]
When uploading eicar to owncloud 10.0.2 with antivirus app enabled and installed on host system
a message occurs "unsupported media type" on the webUI and in the logs:
`"Exception\":\"OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Exception\\\\UnsupportedMediaType\"`

A user reported, that this was done better in earlier versions of owncloud.

**Comment by VicDeo** [comment]
@voroyam The apps returns HTTP and message https://github.com/owncloud/files_antivirus/blob/stable10/lib/avirwrapper.php#L108

But any message is overridden on the core level.

**Comment by michaelstingl** [comment]
In oC 9.1.x, it showed a nice, actionable error message:

> Error uploading file "eicar-av-test.txt": Virus Eicar-Test-Signature is detected in the file. Upload cannot be completed.

@VicDeo Do you mean core overrides this message? Why?

**Comment by michaelstingl** [comment]
@PVince81 I need an assignment here.

**Comment by PVince81** [comment]
@VicDeo please take on this once you're done with all p1. thanks

**Comment by PVince81** [comment]
Likely related to https://github.com/owncloud/core/issues/24304

**Comment by PVince81** [comment]
@VicDeo can you do a quick debug and confirm that the problem is https://github.com/owncloud/core/issues/24304 ? We might then change the priority of that one...

**Comment by VicDeo** [comment]
@PVince81 yes, the real  message of the exception is disposed in a favor of pure HTTP status message.
And it started after switching upload to the DAV endpoint.

**Comment by PVince81** [comment]
Taking over this, I have some local code to parse the Sabre exception and could adjust it for the upload message at least. (other code paths to be done later)

**Comment by PVince81** [comment]
@VicDeo please review and test with https://github.com/owncloud/core/pull/28620
