### ISSUE TITLE
Check/update info.xml stuff

### ISSUE THREAD

**Issue by pmaier1** [owncloud/files_antivirus#172]

**Comment by PVince81** [comment]
@pmaier1 any update ?

**Comment by VicDeo** [comment]
@pmaier1 could we expedite this somehow to fit into 10.04?

**Comment by pmaier1** [comment]
https://github.com/owncloud/files_antivirus/pull/190

**Comment by pmaier1** [comment]
We still want to exchange the screenshot. Thanks for being quick with this but we need to wait a bit. I will do this today!

**Comment by pmaier1** [comment]
https://github.com/owncloud/files_antivirus/pull/191/
