### ISSUE TITLE
missing validation in input fields

### ISSUE THREAD

**Issue by individual-it** [owncloud/files_antivirus#178]
the fields 'Host', 'Port', 'Stream Length' & 'File size limit' should be validated better.
All fields seem to accept any character. At least "Port" and "File size limit" do not save strings that do not look like integer, the other fields do.
But you can enter a "minus" in the port field. e.g. "Port : -3310" and it get saved
In 'Host' and 'Stream Length' its possible to enter any kind of rubbish and it gets saved.

**Comment by PVince81** [comment]
moving to development to work on for next release

**Comment by PVince81** [comment]
backlog

**Comment by individual-it** [comment]
This was first fixed (frontend validation) by #187 but it looks like #195 brought that issue back
after #195 I see red marks around invalid fields but still can save the invalid settings 
![image](https://user-images.githubusercontent.com/2425577/34932455-e6d847ac-f9fa-11e7-8edc-f5ce3bafcef0.png)

**Comment by individual-it** [comment]
fixed by #212
