### ISSUE TITLE
reject file uploads when clamAV is not reachable

### ISSUE THREAD

**Issue by individual-it** [owncloud/files_antivirus#181]
When and admin configures the antivirus app, every upload has to be scanned. If the clamAV service is not reachable for whatever reasons the upload cannot be checked and should be rejected.

This was first suggested by @hodyroff in https://github.com/owncloud/core/issues/28870#issuecomment-326413982

**Comment by PVince81** [comment]
I don't think this is a release blocker -> p2

cc @pmaier1 @felixboehm if you think otherwise

**Comment by PVince81** [comment]
the antivirus should likely throw a proper exception to abort the upload

**Comment by VicDeo** [comment]
To reject upload I should to be  100% sure that upload is in progress.
Any kind of `Storage::fwrite` will be rejected If I just throw an exception.

**Comment by PVince81** [comment]
@VicDeo when does the streaming to clamav start ? Even if we started streaming a few bytes and and only then throw an exception it's fine too
