### ISSUE TITLE
if an app implements own upload endpoints the antivirus is not triggered

### ISSUE THREAD

**Issue by individual-it** [owncloud/files_antivirus#182]
tested with the text editor:
1. create a new file
2. enter the eicar test virus code: `X5O!P%@AP[4\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*`

the antivirus app does not get triggered and the virus file gets saved

**Comment by PVince81** [comment]
I guess the antivirus storage wrapper doesn't intercept "file_put_contents" ?

**Comment by VicDeo** [comment]
@PVince81 it's already known and discussed.

**Comment by PVince81** [comment]
moving to development to work on for next release.

@VicDeo where is the discussion ?

**Comment by PVince81** [comment]
@VicDeo ping, see previous comment

**Comment by VicDeo** [comment]
@PVince81 ook. you asked ;)
https://github.com/owncloud/enterprise/issues/1764
