### ISSUE TITLE
input fields are not aligned correctly

### ISSUE THREAD

**Issue by individual-it** [owncloud/files_antivirus#183]
![image](https://user-images.githubusercontent.com/2425577/29962800-23aed1ce-8f24-11e7-943d-21ab549552b4.png)

**Comment by VicDeo** [comment]
@individual-it browser, screen resolution?
<img width="405" alt="avir" src="https://user-images.githubusercontent.com/991300/30385574-481c3cbe-98b0-11e7-8f96-f04d2d14211c.png">

**Comment by individual-it** [comment]
FF 55 and Chrome 60 both on Debian
Chrome is a little bit different. Also happens on various resolutions
FF:
![ff](https://user-images.githubusercontent.com/2425577/30428952-5dd7aec4-9975-11e7-8ea8-974bf9493d22.gif)
Chrome:
![chrome](https://user-images.githubusercontent.com/2425577/30428948-587c6118-9975-11e7-9d49-8ed78e084e3d.gif)

sorry quality of the gif is not the best

**Comment by PVince81** [comment]
moving to development to work on for next release

**Comment by individual-it** [comment]
seems to be fixed with #187
