### ISSUE TITLE
testplan

### ISSUE THREAD

**Issue by individual-it** [owncloud/files_antivirus#186]
## File antivirus Test Plan
tested server setup: stable10 branch (https://github.com/owncloud/core/commits/18e672eb38a10f267c0fa811c16263241be10747), sqlite DB
file antivirus version: master branch (5c07baa54694bba9ecea7c1127f0cd8c97f7add4)

### Installing the app
| Test Case                                | Expected Result                          | Result | Related Comment |
| ---------------------------------------- | ---------------------------------------- | ------ | --------------- |
| Enable the app in the WebGUI             | No problems found.                       | ☑      |                 |
| Disable and enable the app using CLI.    | No problems found.                       | ☑     |                 |

### Input field validation

| Test Case                                | Expected Result                          | Result | Related Comment |
| ---------------------------------------- | ---------------------------------------- | ------ | --------------- |
| Enter an invalid hostname e.g. 'localhost%&$#+~' and save the antivirus settings | saving is rejected |    ❎      |    #178    |
| Enter a negative number as "Port" and save the antivirus settings | saving is rejected | ❎      |    #178    |
| Enter a floating point number as "Port" and save the antivirus settings | saving is rejected | ❎      |    #178    |
| Enter "0" as "Port" and save the antivirus settings | saving is rejected | ❎      |    #178    |
| Enter a non numerical string as "Port" and save the antivirus settings | saving is rejected | ❎      |    #178    |
| Enter a negative number as "Stream Length" and save the antivirus settings | saving is rejected | ❎      |    #178    |
| Enter a floating point number as "Stream Length" and save the antivirus settings | saving is rejected | ❎      |    #178    |
| Enter a floating point number as "Stream Length" and save the antivirus settings | saving is rejected | ❎      |    #178    |
| Enter a non numerical string as "Stream Length" and save the antivirus settings | saving is rejected | ❎      |    #178    |
| Enter "0" as "Stream Length" and save the antivirus settings | saving is rejected |  ❎      |    #178    |
| Enter a negative number, less than -1 as "File size limit" and save the antivirus settings | saving is rejected |  ❎      |    #178    |
| Enter a floating point number as "File size limit" and save the antivirus settings | saving is rejected |   ❎      |    #178    |
| Enter a non numerical string as "File size limit" and save the antivirus settings | saving is rejected |   ❎      |    #178    |
| Enter "0" as "File size limit" and save the antivirus settings | saving is rejected |  ❎      |    #178    |

### clamAV executable mode upload

1. setup the file antivirus app to use clamAV in "Executable" mode
2. upload `eicar.com`, `eicar_com.zip` and `eicarcom2.zip` from http://www.eicar.org/85-0-Download.html via all available endpoints. (See "Tips how to test different endpoints with curl")

None of these uploads should be possible.

| upload test ↓ Testfile→       | eicar.com | eicar_com.zip | eicarcom2.zip |
| ----------------------------- | --------- | ------------- | ------------- |
| old dav path without chunking	|    ☑      |      ☑        |      ☑        |		
| old dav path with chunking    |    ☑     |       ☑       |      ☑       |
| new dav path without chunking |    ☑     |       ☑       |      ☑       |
| new dav path with chunking    |    ☑     |       ☑       |      ☑       |
| public upload                 |    ☑     |       ☑       |      ☑       |
| files_texteditor app          |    ❎  #182   |       -       |      -        |

### clamAV daemon mode upload

1. setup the file antivirus app to use clamAV in "Daemon" mode
2. upload `eicar.com`, `eicar_com.zip` and `eicarcom2.zip` from http://www.eicar.org/85-0-Download.html via all available endpoints. (See "Tips how to test different endpoints with curl")

None of these uploads should be possible.

| upload test ↓ Testfile→       | eicar.com | eicar_com.zip | eicarcom2.zip |
| ----------------------------- | --------- | ------------- | ------------- |
| old dav path without chunking	|    ☑     |       ☑       |      ☑       |		
| old dav path with chunking    |    ☑     |       ☑      |      ☑       |
| new dav path without chunking |   ☑     |       ☑       |      ☑       |
| new dav path with chunking    |    ☑     |       ☑       |      ☑       |
| public upload                 |    ☑     |       ☑       |      ☑       |
| files_texteditor app          |    ❎  #182   |       -       |      -        |

### clamAV daemon (socket) mode upload

1. setup the file antivirus app to use clamAV in "Daemon (Socket)" mode
2. upload `eicar.com`, `eicar_com.zip` and `eicarcom2.zip` from http://www.eicar.org/85-0-Download.html via all available endpoints. (See "Tips how to test different endpoints with curl")

None of these uploads should be possible.

| upload test ↓ Testfile→       | eicar.com | eicar_com.zip | eicarcom2.zip |
| ----------------------------- | --------- | ------------- | ------------- |
| old dav path without chunking	|    ☑     |       ☑       |      ☑       |		
| old dav path with chunking    |    ☑     |       ☑       |      ☑       |
| new dav path without chunking |    ☑     |       ☑       |      ☑       |
| new dav path with chunking    |    ☑     |       ☑       |      ☑       |
| public upload                 |    ☑     |       ☑       |      ☑       |
| files_texteditor app          |    ❎  #182   |       -       |      -        |

### Filesize limit

set "File size limit" to 100 bytes
uploads of `eicar.com` (68byte) should be blocked
uploads of `eicar_com.zip` (184byte) should pass

| upload test ↓ Testfile→       | eicar.com <br> blocked | eicar_com.zip <br> passing |
| ----------------------------- | ---------------------- | -------------------------- |
| old dav path without chunking	|    ☑                  |       ☑                    |
| old dav path with chunking    |    ☑                  |       ❎  #179              |
| new dav path without chunking |    ☑                  |       ☑                    |
| new dav path with chunking    |    ☑                  |       ❎  #179              |
| public upload                 |    ☑                  |       ☑                    |

### background scan

run these steps between every test case in this chapter:
1. disable antivirus app
2. upload `eicar.com`, `eicar_com.zip` and `eicarcom2.zip` from http://www.eicar.org/85-0-Download.html to the owncloud system under test
3. enable antivirus app
4. set "When infected files were found during a background scan" to "logSetting"
5. set "File size limit" to "fileSizeLimit"
6. wait 15 min (or change `$this->setInterval(60 * 15);` in `lib/cron/task.php` to a smaller number)
7. trigger cron job by running `sudo -u www-data php cron.php`
8. check logfile
9. check files

| Test Case                                | Expected Result                          | Result | Related Comment |
| ---------------------------------------- | ---------------------------------------- | ------ | --------------- |
| logSetting = "Only log"<br>fileSizeLimit="-1" | 1. `eicar.com`, `eicar_com.zip` and `eicarcom2.zip` are logged as infected<br>2. all files still exist on the system | ☑     |                 |
| logSetting = "Only log"<br>fileSizeLimit="100" | 1. only `eicar.com` is logged as infected<br>2. all files still exist on the system | ☑     |                 |
| logSetting = "Delete file"<br>fileSizeLimit="-1" | 1. `eicar.com`, `eicar_com.zip` and `eicarcom2.zip` are logged as infected and deleted<br>2. `eicar.com`, `eicar_com.zip` and `eicarcom2.zip` disappear from the system | ☑     |                 |
| logSetting = "Delete file"<br>fileSizeLimit="100" | 1. only `eicar.com` is logged as infected  and deleted<br>2. only `eicar.com` disappears from the system | ☑     |                 |

**Comment by patrickjahns** [comment]
Should this testplan be moved to QA repository as template and then closed?

**Comment by individual-it** [comment]
testplan template is here https://github.com/owncloud/QA/blob/master/Server/Test_Plan_Files_Antivirus.md
