### ISSUE TITLE
Look for a better way to bypass going to trashbin

### ISSUE THREAD

**Issue by VicDeo** [owncloud/files_antivirus#199]
instead of 
```
				if (App::isEnabled('files_trashbin')) {
					\OCA\Files_Trashbin\Storage::preRenameHook([
						Filesystem::signal_param_oldpath => '',
						Filesystem::signal_param_newpath => ''
					]);
				}
				$this->unlink($path);
				if (App::isEnabled('files_trashbin')) {
					\OCA\Files_Trashbin\Storage::postRenameHook([]);
				}
```

**Comment by micbar** [comment]
@VicDeo maybe talk to @JanAckermann about his recent core contrib.

**Comment by VicDeo** [comment]
If https://github.com/owncloud/core/pull/38704 is meant I see no way to use it here.

**Comment by VicDeo** [comment]
Well, this code is no longer needed after https://github.com/owncloud/files_antivirus/pull/373

I've submitted https://github.com/owncloud/files_antivirus/pull/452 to remove it.
