### ISSUE TITLE
Antivirus Configuration fails when saved

### ISSUE THREAD

**Issue by juamargo** [owncloud/files_antivirus#202]
After update to version 0.11.2, I can't change configuration of this app. Button "Save" has not reaction, and content of fields get back to previous values.

**Comment by juamargo** [comment]
I've resolved this issue deleting the 'file_antivirus' rows in the 'oc_appconfig' table in the MySql database, and reinstalling the app.

**Comment by VicDeo** [comment]
closing as self-resolved as nobody else had the same issue.
In 0.12.0 settings are saved with ajax anyway.
