### ISSUE TITLE
0.12.0 Release plan

### ISSUE THREAD

**Issue by pmaier1** [owncloud/files_antivirus#204]
**Reason**
- Release needed for
feature #180, the app should  check the reachability of clamAV when saving the settings
feature #181 If the clamAV service is not reachable for whatever reasons the upload cannot be checked and should be rejected.
bugfix #179, files of any size get checked regardless of the "File size limit" setting when chunking is used
bugfix #182 it is possible to save a signature with text_editor app

**QA**
- [x] Create release branch **release/0.12.0** https://github.com/owncloud/files_antivirus/pull/203
- [x] Create "$version Testplan"
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label)

**Marketing**
- [ ] Check/adapt info.xml stuff
- [ ] Check/adapt screenshot

**Documentation**
- [x] Changes in the docs needed https://github.com/owncloud/documentation/issues/3628
- Unconfigured/Misconfigured app rejects upload **by design**.
- Unavailable clamav rejects upload **by design**.
- Filesize limit applies both to background job and upload now (only bg job in past)
- (Top FAQ question) individual chunks are not scanned, the whole file is scanned on moving to the final location
- There is a popup that notifies admin on save that settings are incorrect :
![misconfig-daemon](https://user-images.githubusercontent.com/991300/33023080-230bf69c-ce18-11e7-8b4e-41b7cbb7c605.png)
![misconfig-socket](https://user-images.githubusercontent.com/991300/33023083-24aa9742-ce18-11e7-8ece-de89ebe676b5.png)
![misconfig-executable](https://user-images.githubusercontent.com/991300/33023089-26659e4c-ce18-11e7-8340-cba3fc636803.png)

**Build & Marketplace release**

- [x] Bump version in info.xml
- [x] Update CHANGELOG.md
- [x] Create github tag for '$version'
- [x] Build and sign tarball from github tag '$version'
- [x] Upload to marketplace
- [x] Rename QA milestone to '$version'
- [ ] Change CHANGELOG.md 'Unreleased' to '$version' and add a new 'Unreleased' section
- [x] Create PR to merge changes back to `master`

**Comment by VicDeo** [comment]
There is a testplan from a previous version that could be handy https://github.com/owncloud/files_antivirus/issues/186

**Comment by individual-it** [comment]
test-results in #210 
the draft test plan can be found in https://github.com/owncloud/QA/blob/master/Server/Test_Plan_Files_Antivirus.md

**Comment by pmaier1** [comment]
Docs have been adapted https://github.com/owncloud/documentation/pull/3645

**Comment by patrickjahns** [comment]
closed as #203 has been merged
