### ISSUE TITLE
[Feature Request] occ commands to configure files_antivirus 

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/files_antivirus#205]
On our quest to have all apps configurable to automate stuff - It'd be nice to have a way to do this with antivirus. This way I can launch a container stack with ownCloud and configure it to connect to a clamav daemon running on a different container. 

Available settings for reference:

<p align="center">
  <img src="https://user-images.githubusercontent.com/2644445/34041095-f9f08f60-e196-11e7-9c5a-7c560bbf4fc6.png"/>
</p>

**Comment by VicDeo** [comment]
@SamuAlfageme 
`php occ config:list | grep av_`
`php occ config:app:set files_antivirus whatever_key value `

**Comment by SamuAlfageme** [comment]
@VicDeo neat! this will do. 

Would be cool however to add some syntactic sugar to make it easier/shorter to configure: e.g. `occ files_antivirus:daemon clamav:3310`

But this is definitely enough to close. Thanks!
