### ISSUE TITLE
chunked files (old algorithm) don't get checked

### ISSUE THREAD

**Issue by individual-it** [owncloud/files_antivirus#208]
1. set up the app and make sure it blocks `eicar.com` from http://www.eicar.org/85-0-Download.html
2. setup variables:
```
user=admin
pwd=admin
host=localhost
path=owncloud
```
3. split file for chunking
`split -d -b 50 eicar.com eicar.com_`

4. upload with chunking:
```
curl --user $user:$pwd http://$host/$path/remote.php/webdav/virus-chunking-1234-2-0 --request PUT --data-binary "@eicar.com_00" -H "OC-Chunked:1"
curl --user $user:$pwd http://$host/$path/remote.php/webdav/virus-chunking-1234-2-1 --request PUT --data-binary "@eicar.com_01" -H "OC-Chunked:1"
```

The problem was introduced by #196

**Comment by VicDeo** [comment]
Well, I don't know how to fix it properly.
The only solution is to  scan dav v1 chunks

**Comment by PVince81** [comment]
Didn't it work before for old chunking ? I thought it would check the file during final assembly ?

**Comment by PVince81** [comment]
closed by https://github.com/owncloud/files_antivirus/pull/211

**Comment by VicDeo** [comment]
@PVince81
>Didn't it work before for old chunking ? I thought it would check the file during final assembly ?

yes, since chunks were scanned before. 
But since version 0.12.0 aka "still unreleased" chunks are skipped for performance reasons and only the final file is scanned.
