### ISSUE TITLE
public uploads don't get checked

### ISSUE THREAD

**Issue by individual-it** [owncloud/files_antivirus#209]
1. set up the app and make sure it blocks `eicar.com` from http://www.eicar.org/85-0-Download.html
2. create an public link with upload permissions
3. upload `eicar.com`

The problem was introduced by #196

**Comment by PVince81** [comment]
@VicDeo please investigate

**Comment by PVince81** [comment]
closed by https://github.com/owncloud/files_antivirus/pull/211
