### ISSUE TITLE
Use --fdpass with clamdscan

### ISSUE THREAD

**Issue by koehn** [owncloud/files_antivirus#21]
If the path to `clamscan` is actually a path to `clamdscan`, the app should (possibly optionally) pass the `--fdpass` parameter to force `clamdscan` to pass the file descriptor to the `clamav` daemon. [This is faster and it allows the daemon to process files to which it wouldn't otherwise have read access](http://linux.die.net/man/1/clamdscan). 

Administrators **cannot** currently affect this change manually by specifying a path to (for example) `/usr/local/bin/clamdscan --fdpass `. Instead, administrators can work around the issue by creating the following script and supply a path to it instead:

````
#!/bin/bash

/usr/local/bin/clamdscan --fdpass $@
````

**Comment by VicDeo** [comment]
@koehn at least  master/stable8/stable7 has this option: 
![5st](https://cloud.githubusercontent.com/assets/991300/6488203/e1a1d584-c2a6-11e4-9d5f-c0ee3c111d19.png)

**Comment by sorglos** [comment]
> at least master/stable8/stable7 has this option

stable8 and master but not stable7

**Comment by VicDeo** [comment]
@sorglos sorry, enhancements are not backportable.

**Comment by sorglos** [comment]
@VicDeo Okay, no problem.

**Comment by VicDeo** [comment]
Closing as implemented.
