### ISSUE TITLE
0.12.0 testplan

### ISSUE THREAD

**Issue by individual-it** [owncloud/files_antivirus#210]
## File antivirus Test Plan
tested server setup: stable10 branch (v10.0.5RC3), sqlite DB
file antivirus version: 0.12.0 (https://github.com/owncloud/files_antivirus/pull/203)

### Installing the app
| Test Case                                | Expected Result                          | Result | Related Comment |
| ---------------------------------------- | ---------------------------------------- | ------ | --------------- |
| Enable the app in the WebGUI             | No problems found.                       | ☑      |                 |
| Disable and enable the app using CLI.    | No problems found.                       | ☑     |                 |

### Input field validation

| Test Case                                | Expected Result                          | Result | Related Comment |
| ---------------------------------------- | ---------------------------------------- | ------ | --------------- |
| Enter an invalid hostname e.g. 'localhost%&$#+~' and save the antivirus settings | saving is rejected |    ☑      |       |
| Enter a negative number as "Port" and save the antivirus settings | saving is rejected | ☑      |       |
| Enter a floating point number as "Port" and save the antivirus settings | saving is rejected | ☑      |       |
| Enter "0" as "Port" and save the antivirus settings | saving is rejected | ☑      |       |
| Enter a non numerical string as "Port" and save the antivirus settings | saving is rejected | ☑      |       |
| Enter a negative number as "Stream Length" and save the antivirus settings | saving is rejected | ☑      |       |
| Enter a floating point number as "Stream Length" and save the antivirus settings | saving is rejected | ☑      |       |
| Enter a floating point number as "Stream Length" and save the antivirus settings | saving is rejected | ☑      |       |
| Enter a non numerical string as "Stream Length" and save the antivirus settings | saving is rejected |☑      |       |
| Enter "0" as "Stream Length" and save the antivirus settings | saving is rejected |  ☑      |       |
| Enter a negative number, less than -1 as "File size limit" and save the antivirus settings | saving is rejected |  ☑      |       |
| Enter a floating point number as "File size limit" and save the antivirus settings | saving is rejected |   ☑      |       |
| Enter a non numerical string as "File size limit" and save the antivirus settings | saving is rejected |   ☑      |       |
| Enter "0" as "File size limit" and save the antivirus settings | saving is rejected |  ☑      |       |

### clamAV executable mode upload

1. setup the file antivirus app to use clamAV in "Executable" mode
2. upload `eicar.com`, `eicar_com.zip` and `eicarcom2.zip` from http://www.eicar.org/85-0-Download.html via all available endpoints. (See "Tips how to test different endpoints with curl")

None of these uploads should be possible.

| upload test ↓ Testfile→       | eicar.com | eicar_com.zip | eicarcom2.zip |
| ----------------------------- | --------- | ------------- | ------------- |
| old dav path without chunking	|    ☑      |     ☑         |       ☑       |		
| old dav path with chunking    | ☑ #211    |  ☑ #211      |   ☑ #211      |
| new dav path without chunking |    ☑      |     ☑         |       ☑       |
| new dav path with chunking    |    ☑      |     ☑         |       ☑       |
| public upload                 | ☑ #211    |  ☑ #211      |   ☑ #211      |
| files_texteditor app          | ☑  #198   |      -       |      -        |

### clamAV daemon mode upload

1. setup the file antivirus app to use clamAV in "Daemon" mode
2. upload `eicar.com`, `eicar_com.zip` and `eicarcom2.zip` from http://www.eicar.org/85-0-Download.html via all available endpoints. (See "Tips how to test different endpoints with curl")

None of these uploads should be possible.

| upload test ↓ Testfile→       | eicar.com | eicar_com.zip | eicarcom2.zip |
| ----------------------------- | --------- | ------------- | ------------- |
| old dav path without chunking	|    ☑      |     ☑         |       ☑       |		
| old dav path with chunking    | ☑ #211    |  ☑ #211      |   ☑ #211      |
| new dav path without chunking |    ☑      |     ☑         |       ☑       |
| new dav path with chunking    |    ☑      |     ☑         |       ☑       |
| public upload                 | ☑ #211    |  ☑ #211      |   ☑ #211      |
| files_texteditor app          | ☑  #198   |      -       |      -        |

### clamAV daemon (socket) mode upload

1. setup the file antivirus app to use clamAV in "Daemon (Socket)" mode
2. upload `eicar.com`, `eicar_com.zip` and `eicarcom2.zip` from http://www.eicar.org/85-0-Download.html via all available endpoints. (See "Tips how to test different endpoints with curl")

None of these uploads should be possible.

| upload test ↓ Testfile→       | eicar.com | eicar_com.zip | eicarcom2.zip |
| ----------------------------- | --------- | ------------- | ------------- |
| old dav path without chunking	|    ☑      |     ☑         |       ☑       |		
| old dav path with chunking    | ☑ #211    |  ☑ #211      |   ☑ #211      |
| new dav path without chunking |    ☑      |     ☑         |       ☑       |
| new dav path with chunking    |    ☑      |     ☑         |       ☑       |
| public upload                 | ☑ #211    |  ☑ #211      |   ☑ #211      |
| files_texteditor app          | ☑  #198   |      -       |      -        |

### Filesize limit

set "File size limit" to 100 bytes
uploads of `eicar.com` (68byte) should be blocked
uploads of `eicar_com.zip` (184byte) should pass

| upload test ↓ Testfile→       | eicar.com <br> blocked | eicar_com.zip <br> passing |
| ----------------------------- | ---------------------- | -------------------------- |
| old dav path without chunking	|    ☑                  |       ☑                    |
| old dav path with chunking    |    ☑             |       ❎  #179                |
| new dav path without chunking |    ☑                  |       ☑                    |
| new dav path with chunking    |    ☑                  |       ❎  #179              |
| public upload                 |    ☑ #211            |       ☑                    |

### background scan

run these steps between every test case in this chapter:
1. disable antivirus app
2. upload `eicar.com`, `eicar_com.zip` and `eicarcom2.zip` from http://www.eicar.org/85-0-Download.html to the owncloud system under test
3. enable antivirus app
4. set "When infected files were found during a background scan" to "logSetting"
5. set "File size limit" to "fileSizeLimit"
6. wait 15 min (or change `$this->setInterval(60 * 15);` in `lib/cron/task.php` to a smaller number)
7. trigger cron job by running `sudo -u www-data php cron.php`
8. check logfile
9. check files

| Test Case                                | Expected Result                          | Result | Related Comment |
| ---------------------------------------- | ---------------------------------------- | ------ | --------------- |
| logSetting = "Only log"<br>fileSizeLimit="-1" | 1. `eicar.com`, `eicar_com.zip` and `eicarcom2.zip` are logged as infected<br>2. all files still exist on the system | ☑     |                 |
| logSetting = "Only log"<br>fileSizeLimit="100" | 1. only `eicar.com` is logged as infected<br>2. all files still exist on the system | ☑     |                 |
| logSetting = "Delete file"<br>fileSizeLimit="-1" | 1. `eicar.com`, `eicar_com.zip` and `eicarcom2.zip` are logged as infected and deleted<br>2. `eicar.com`, `eicar_com.zip` and `eicarcom2.zip` disappear from the system | ☑     |                 |
| logSetting = "Delete file"<br>fileSizeLimit="100" | 1. only `eicar.com` is logged as infected  and deleted<br>2. only `eicar.com` disappears from the system | ☑     |                 |

**Comment by patrickjahns** [comment]
@individual-it 
#179 will be added to the "known-issues" and is not a release blocker

Regarding #178 -> will ping victor on an ETA and decide if known issue or we fix it for the release

**Comment by patrickjahns** [comment]
closing - has been released
