### ISSUE TITLE
Error uploading file: OC_FileChunking:

### ISSUE THREAD

**Issue by dani-sanchez-dorado** [owncloud/files_antivirus#216]
Hello, 
I have just updated the files_antivirus app to 0.12.0 and I get this error when I upload a file: 

Feb 20 09:49:58 <server> apache2[2833]: {PHP} Call to undefined method OC_FileChunking::isWebdavChunk() at /home/soft/owncloud-10.0.1/apps/files_antivirus/lib/RequestHelper.php#42

My system info is:

Operating System: Ubuntu 16.04.02 LTS
Web server: Apache
Database: MySQL
PHP version: 5.6.30-11
ownCloud version: 10.0.1
Antivirus App for files 0.12.0
Clamav version:
 /home/soft/clamav/bin/clamscan --version 
ClamAV 0.99.3/24330/Mon Feb 19 18:19:05 2018

Any idea?

Thank you.

**Comment by VicDeo** [comment]
@dani-sanchez-dorado 
oops, `OC_FileChunking::isWebdavChunk`   was added in 10.0.3

**Comment by dani-sanchez-dorado** [comment]
Ok!
then, do you think that be interesting to put a restriction in installation process about owncloud version?  
I will be good for other users. 

Thank you !

**Comment by VicDeo** [comment]
@patrickjahns we might need a quickfix app release for this.

**Comment by VicDeo** [comment]
@dani-sanchez-dorado 
you can copy the implementation (5 lines) from
https://github.com/owncloud/core/blob/master/lib/private/legacy/filechunking.php#L42-L47

**Comment by dani-sanchez-dorado** [comment]
Great!

 I have patched my owncloud and now works perfect!

Thank you very much!
