### ISSUE TITLE
Track file modifications in bg scanner

### ISSUE THREAD

**Issue by VicDeo** [owncloud/files_antivirus#218]
There is no need to rescan files if the content hasn't changed.
We'd better have an attribution to the file content using `eTag` for bg scanner ad trigger rescan if `eTag` of the avir differs from fiile `etag`.
In addition there should be a filter on a scantime in order not to stuck with the same set of frequently changed files.

**Comment by tomneedham** [comment]
Could even just use Redis to cache etags and fileids of files that have been scanned and skip them. Would improve performance whilst redis cache is present, and still be secure if the cache is lost. 

Thoughts?

@pmaier1

**Comment by pmaier1** [comment]
@PVince81 would be nice to schedule this as it's pretty unnecessary to always rescan all files. 

> Could even just use Redis to

Only if the solution works without redis, too, please.

**Comment by PVince81** [comment]
@VicDeo can you estimate ?

**Comment by VicDeo** [comment]
As soon as the eTag  at the moment of scanning is currently unknown and there is a possibility that content has been changed by the moment of update I would suggest either to drop `files_antivirus` table completely and recreate an empty table with new fields or add a new column into  `files_antivirus` and truncate the data.


estimate is 1-2 md.
