### ISSUE TITLE
App description needs an updated description

### ISSUE THREAD

**Issue by MTRichards** [owncloud/files_antivirus#22]
in the antivir app admin page we ask for the path to clamscan. I thought we also support other anti-virus solutions? Then we need to call this field "Link to virus scanner - e.g. /usr/bin/clamscan" or similar. If this app only supports ClamAV we need to change the app description to say that. Right now the app description reads as if you can use different scanners.

**Comment by DeepDiver1975** [comment]
@MTRichards what should the app description look like? THX

**Comment by DeepDiver1975** [comment]
The current app description got changed back in https://github.com/owncloud/files_antivirus/commit/c6df80eec0af4e5f9071d8f4566844a962319180

**Comment by jnfrmarks** [comment]
@DeepDiver1975 

Is this a change for 8.0.1?

**Comment by DeepDiver1975** [comment]
8.0.1 is closed from my pov - any changes in what ever repo go into 8.0.2

**Comment by jnfrmarks** [comment]
Agreed

**Comment by VicDeo** [comment]
@MTRichards In general it should work not with clamscan but with any shell scanner  that is capable to read content from STDIN. 
This has been never tested and requires defining own rules at the 'Advanced' section. 
I spent some time to find another free antivirus for Linux and found nothing appropriate.
Comodo Free Antivirus refused to start its daemon so I didn't go further in this direction.

**Comment by DeepDiver1975** [comment]
let's tick with clamav for now as the tested configuration.

**Comment by MTRichards** [comment]
@VicDeo Interesting - we should look into testing this in future releases once we have a better handle on the integration, what vendors support this, and have a chance to try it out.

**Comment by DeepDiver1975** [comment]
@MTRichards What shall we write into the app description now? The current description is totally broken - THX

**Comment by DeepDiver1975** [comment]
It contains the description of files_locking :rocket: 

https://github.com/owncloud/files_antivirus/blob/master/appinfo/info.xml#L7

**Comment by MTRichards** [comment]
How about this:
This application inspects files that are uploaded to ownCloud for viruses before they are written to the ownCloud storage. If a file is identified as a virus, it is either logged or not uploaded to the server. The application relies on the underlying ClamAV virus scanning engine, which the admin points ownCloud to when configuring the application. 
For this app to be effective, the ClamAV virus definitions should be kept up to date. Also note that enabling this app will impact system performance as additional processing is required for every upload. More information is available in the Antivirus documentation.

**Comment by DeepDiver1975** [comment]
@VicDeo can you please adopt the description as proposed by @MTRichards above? THX

**Comment by VicDeo** [comment]
@MTRichards @DeepDiver1975 done https://github.com/owncloud/files_antivirus/pull/28
