### ISSUE TITLE
jQuery Core 1.9 Upgrade Guide

### ISSUE THREAD

**Issue by felixheidecke** [owncloud/files_antivirus#241]
# jQuery Core 1.9 Upgrade Guide

Changes of Note in jQuery 1.9
See the full [upgrade guide at jquery.com](http://jquery.com/upgrade-guide/1.9/)

## Minor

`.trigger()`

- [x] /js/settings.js

`.focus()`

- [x] /js/settings.js

`.data()`

- [x] /js/settings.js

`.parents()`

- [x] /js/settings.js

`.focus()`

- [x] /js/settings.js

`.attr()`

- [x] /js/settings.js

`.toggle()`

- [x] /js/settings.js

`.appendTo()`

- [x] /js/settings.js

**Comment by VicDeo** [comment]
mmm. I'm loosing the track what should be done here... testing?

**Comment by felixheidecke** [comment]
@VicDeo The methods above are those who "might" have changed in jQuery 1.9 and 2.x respectively, so these need to be checked if they break on upgrading to jquery 2. I am preparing a core branch with jquery 2 for testing purposes.

**Comment by felixheidecke** [comment]
Please use https://github.com/owncloud/core/tree/jquery-2-migration for testing jquery 2
