### ISSUE TITLE
at least odt, ods, pdf not scanned

### ISSUE THREAD

**Issue by viegelinsch** [owncloud/files_antivirus#25]
My logfile shows the message `could not be scanned. Details: No matching rule for exit code -1. Please check antivirus rules configuration.` for file of type odt, ods, pdf at least.

I would appreciate a documentation where I need to configure this rules.   
Help appreciated.

**Comment by VicDeo** [comment]
@viegelinsch Admin page -> Antivirus Configuration -> Advanced -> Reset to defaults

**Comment by viegelinsch** [comment]
Strange nothing changed there since installation but this fixed the problem.
Thank you!!!
