### ISSUE TITLE
Antivirus 0.15.0

### ISSUE THREAD

**Issue by PVince81** [owncloud/files_antivirus#285]
### Reason
- [x] debug log in background job: https://github.com/owncloud/files_antivirus/pull/260#issuecomment-447906670
- [x] Do not scan files if etag hasn't changed https://github.com/owncloud/files_antivirus/pull/288

### QA
- [x] Create **QA Milestone**
- [x] Move items from `development` to `qa` 
- [x] Create release branch with the format "release-$version"
- [x] Create "0.15.0 Testplan" @davitol https://github.com/owncloud/files_antivirus/issues/298

### Documentation
- [ ] Changes in the docs needed?

### Marketing
- [ ] Ping RocketChat channel #marketing
- [ ] Check/adapt info.xml stuff
- [ ] Check/adapt screenshot
- [ ] Blog post or other communication if applicable

### Build & Marketplace release

All actions to be done on the release branch from here:
- [x] Bump version in info.xml
- [x] Update CHANGELOG.md - Change CHANGELOG.md 'Unreleased' to '$version' (final release date unknown)
- [x] Create github tag for 'v${version}RC1'
- [x] Build and sign RC tarball from github tag 'v${version}RC1' with `make dist` and upload as Github release: https://github.com/owncloud/files_antivirus/releases/tag/v0.15.0RC1
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing
- [x] Create github tag for final 'v${version}'
- [x] Build and sign final tarball from github tag 'v${version}' with `make dist` and upload as Github release
- [x] Smoke test tarball (at least install + enable)
- [x] Upload to marketplace
- [x] Publish for customers
- [x] Send mail to release-coordination with link to this ticket and to the changelog
- [x] Rename QA milestone to '$version'
- [x] Add a new 'Unreleased' section in CHANGELOG.md and add release date '$version - $currentDate' (ex: 3.1.5 - 2018-08-01)
- [x] Create PR to merge changes back to the `master` branch

**Comment by PVince81** [comment]
since https://github.com/owncloud/files_antivirus/pull/288 looks like a bigger change, increasing version to 0.15.0

**Comment by PVince81** [comment]
RC1 is out https://github.com/owncloud/files_antivirus/releases/tag/v0.15.0RC1 @davitol

**Comment by davitol** [comment]
@PVince81 Tarball is QA-ready
