### ISSUE TITLE
Translations not working when virus is found

### ISSUE THREAD

**Issue by patrickjahns** [owncloud/files_antivirus#291]
When uploading a file (eircar.txt) the message "Virus Eicar-Test-Signature is detected in the file. Upload cannot be completed" can be seen. However, when setting a default language other than english, the message is still displayed in english 

# steps to reproduce
- set owncloud to a different language
- upload eicar.txt file
- see "Virus Eicar-Test-Signature is detected in the file. Upload cannot be completed" banner

# expected behvaior
- translated string should be shown

# actual behavior
- "Virus Eicar-Test-Signature is detected in the file. Upload cannot be completed"

![image](https://user-images.githubusercontent.com/6403243/52091200-e43baa80-25b3-11e9-89d4-8382f94f015d.png)

**Comment by VicDeo** [comment]
Seems to be fixed some time ago

![StaticShot_21-05-2021_04-00-31](https://user-images.githubusercontent.com/991300/119066772-32755180-b9e9-11eb-9ef5-748e75fa3b93.png)
