### ISSUE TITLE
exception: Module with id: OC_DEFAULT_MODULE does not exist.

### ISSUE THREAD

**Issue by individual-it** [owncloud/files_antivirus#305]
1. install oC 10.2.0RC1 and current files_antivirus release
2. wait for cron job to run or force run it with `occ background:queue:execute <id> -f`

the expected messages are not logged but `{"reqId":"4WBQNm21mwlIIRCRPk7b","level":3,"time":"2019-04-23T08:46:04+00:00","remoteAddr":"","user":"admin","app":"files_antivirus","method":"--","url":"--","message":"OCA\\Files_Antivirus\\Cron\\Task::run, exception: Module with id: OC_DEFAULT_MODULE does not exist."}`

**Comment by PVince81** [comment]
@individual-it was this with encryption enabled or disabled ?

the error message is from encryption, as if the "encryption" app was disabled but core encryption enabled.

cc @sharidas

**Comment by individual-it** [comment]
@PVince81 true, closing
