### ISSUE TITLE
test antivirusFileSize.feature:13 fails

### ISSUE THREAD

**Issue by phil-davis** [owncloud/files_antivirus#340]
Last night: https://drone.owncloud.com/owncloud/files_antivirus/1038/24/12
and https://drone.owncloud.com/owncloud/files_antivirus/1038/19/12
```
--- Failed scenarios:

    /var/www/owncloud/testrunner/apps/files_antivirus/tests/acceptance/features/apiAntivirus/antivirusFileSize.feature:13

29 scenarios (28 passed, 1 failed)
295 steps (292 passed, 1 failed, 2 skipped)
```

```
  Scenario: Files smaller than the upload threshold are checked for viruses                                                 # /var/www/owncloud/testrunner/apps/files_antivirus/tests/acceptance/features/apiAntivirus/antivirusFileSize.feature:13
    Given parameter "av_max_file_size" of app "files_antivirus" has been set to "100"                                       # FeatureContext::serverParameterHasBeenSetTo()
    When user "user0" uploads file "eicar.com" from the antivirus test data folder to "/virusfile.txt" using the WebDAV API # AntivirusContext::userUploadsFileFromAntivirusDataFolderTo()
    Then the HTTP status code should be "403"                                                                               # FeatureContext::theHTTPStatusCodeShouldBe()
      HTTP status code is not the expected value
      Failed asserting that 201 matches expected '403'.
    And the last lines of the log file should contain log-entries containing these attributes:                              # AntivirusContext::theLastLinesOfTheLogFileShouldContainEntriesWithTheseAttributes()
      | user  | app             | method | message               |
      | user0 | files_antivirus | PUT    | Infected file deleted |
    And as "user0" file "/virusfile.txt" should not exist                                                                   # FeatureContext::asFileOrFolderShouldNotExist()
```

**Comment by phil-davis** [comment]
@HariBhandari07 this started failing last night. Please assign someone to investigate.

**Comment by HariBhandari07** [comment]
@phil-davis I have run the failing scenario multiple times in this PR https://github.com/owncloud/files_antivirus/pull/341 and it passes. Should we close this issue and just declare it flakey.

**Comment by phil-davis** [comment]
Maybe this is a timing issue and in drone we need to wait a bit until the AV service is up-and-running.
(something similar to what we did for the elastic search service)
We could put in a `wait-for-it` anyway - just need to work out what exactly to wait for ;)

**Comment by phil-davis** [comment]
Failed again last night https://drone.owncloud.com/owncloud/files_antivirus/1050/28/15
```
--- Failed scenarios:

    /var/www/owncloud/testrunner/apps/files_antivirus/tests/acceptance/features/apiAntivirus/antivirusFileSize.feature:13

29 scenarios (28 passed, 1 failed)
295 steps (292 passed, 1 failed, 2 skipped)
```

**Comment by skshetry** [comment]
This has been fixed by #342. Nightly passed with flying colors: https://drone.owncloud.com/owncloud/files_antivirus/1053

**Comment by phil-davis** [comment]
Sadly, https://drone.owncloud.com/owncloud/files_antivirus/1062/31/15
```
--- Failed scenarios:

    /var/www/owncloud/testrunner/apps/files_antivirus/tests/acceptance/features/apiAntivirus/antivirusFileSize.feature:13

29 scenarios (28 passed, 1 failed)
295 steps (292 passed, 1 failed, 2 skipped)
```
but it did wait for clamav:
https://drone.owncloud.com/owncloud/files_antivirus/1062/31/13
```
+ cd /var/www/owncloud/server
+ wait-for-it -t 60 clamav:3310
services are ready!
+ php occ config:app:set --value "clamav" files_antivirus av_host
Config value av_host for app files_antivirus set to clamav
+ php occ config:app:set --value "daemon" files_antivirus av_mode
Config value av_mode for app files_antivirus set to daemon
+ php occ config:app:set --value "3310" files_antivirus av_port
Config value av_port for app files_antivirus set to 3310
```

The scenario that fails is always that first scenario, and usually it passes. So this does seem to be timing problem.

What else to wait for? Or do we give in and add an extra hard-coded 10 second wait after `wait-for-it -t 60 clamav:3310` ?

**Comment by phil-davis** [comment]
@dpakach @HariBhandari07 @skshetry do you have any better ideas?

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/files_antivirus/1065/24/12
failed the same again last night.
maybe we have to put a hard-coded wait for 1 minute after waiting for clamav?

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/files_antivirus/1068/19/12
This failed on a later scenario:
```
--- Failed scenarios:

    /var/www/owncloud/testrunner/apps/files_antivirus/tests/acceptance/features/apiAntivirus/antivirusFileSize.feature:42

29 scenarios (28 passed, 1 failed)
295 steps (292 passed, 1 failed, 2 skipped)
```
???

**Comment by phil-davis** [comment]
Fix has been done in PR #340 to use a modified `clamavd`

**Comment by micbar** [comment]
Let us wait for @VicDeo

**Comment by VicDeo** [comment]
@phil-davis @micbar what exactly is needed from my side here?

**Comment by micbar** [comment]
@VicDeo There were failures in nightly CI due to timing issues.

Currently they are using a custom docker image.
This solution should not be permanent.

@felixboehm This would need DevOps Efforts to include these changes and host the image  from owncloudci

**Comment by VicDeo** [comment]
@micbar it doesn't look like  an app issue to me. 
If I'm not mistaken the test is supposed to pass but the originally used clamav docker image need some time to populate virus DB (unlike the distribution package it is shipped with no DB at all).

So the docker container reports it is started but
1. it has no virus signatures initially
2. it is not possible to detect the point in time when the virus database is ready due to `freshclam` executed in background:
https://github.com/dinkel/docker-clamavd/blob/master/run.sh#L4

**Comment by micbar** [comment]
@VicDeo it is not an app issue, it is an CI issue.

**Comment by VicDeo** [comment]
what I can suggest here 
1. some kind of script that checks whether DB is ready
2. use any other clamav image instead of `dinkel/docker-clamavd` as we need eicar signature only.

**Comment by skshetry** [comment]
@VicDeo, we moved to https://github.com/JankariTech/docker-clamavd which is maintained currently by JankariTech.

**Comment by phil-davis** [comment]
ownCloud could make the same `docker-clamavd` image in `owncloud-ci` and then we switch to using that.

We made the JankariTech image over Christmas-New-Year because most ownCloud people were on leave. The changes in that image have proved to be more reliable in CI.

**Comment by micbar** [comment]
@felixboehm for assigning devops resources.

**Comment by phil-davis** [comment]
@xoxys is this something that you (or some devops/sysadmin person)?
Or who do I ask to do this?

We want to make an `owncloudci/clamavd` that is the same as `jankaritechnepal/clamavd`
(so that ownCloud CI  does not depend on that JankariTech image)

**Comment by xoxys** [comment]
@phil-davis @micbar  In the best case you will do it by your own. I can create an empty repo in owncloud-ci org and I can do PR reviews or help with some parts if needed. @phil-davis I've also sent you an invitation to the CI org

**Comment by phil-davis** [comment]
@xoxys yes, please create an empty repo and I will put stuff in it.
(then I might need help to publish it - depends what privs I have on the docker publishing side)

**Comment by xoxys** [comment]
@phil-davis Done. https://github.com/owncloud-ci/clamavd I've also added the boilerplate to the new repo and enabled drone.

**Comment by phil-davis** [comment]
Assigned myself to sort out the new owncloudci/clamavd repo. (Probably tomorrow)

**Comment by xoxys** [comment]
If you need something, please ping me

**Comment by phil-davis** [comment]
ToDo:
- [ ] sort out https://github.com/owncloud-ci/clamavd so it provides a clamav docker
- [ ] adjust CI here to use owncloudci/clamavd
