### ISSUE TITLE
Scan fails on big compressed files

### ISSUE THREAD

**Issue by voroyam** [owncloud/files_antivirus#370]
The clamAV has issues with large compressed files when uploading.

Customer reports that after a successful upload the file is stuck at ownCloud in the status bar at "Processing files" and the clamd processes runs with 100% CPU load. Customer waited for 45 min but no changes. Restarting the clamd process reduces the load, but the webUI process bar still claims "processing files".

---

Questions:

What command do we use to scan the files?

Can we integrate this option in to the scan to skip compressed uploads?

```
   --scan-archive[=yes(*)/no]
          Scan  archives  supported  by  libclamav.  If  you turn off this
          option, the original files will still be  scanned,  but  without
          unpacking and additional processing.
```

----

Test output of the customer:

```
debcloud01-prod >> ~ : dd if=/dev/urandom of=/tmp/bla.dd bs=1M count=1000

1000+0 Datensätze ein

1000+0 Datensätze aus

1048576000 Bytes (1,0 GB, 1000 MiB) kopiert, 9,22912 s, 114 MB/s

xdebcloud01-prod >> ~ : zip -e /tmp/bla.dd.zip /tmp/bla.dd

Enter password:

Verify password:

updating: tmp/bla.dd (deflated 0%)

xdebcloud01-prod >> ~ : clamscan /tmp/bla.dd.zip

LibClamAV Warning: fmap: map allocation failed

LibClamAV Error: CRITICAL: fmap() failed

/tmp/bla.dd.zip: Can't allocate memory ERROR



----------- SCAN SUMMARY -----------

Known viruses: 7228369

Engine version: 0.102.1

Scanned directories: 0

Scanned files: 0

Infected files: 0

Total errors: 1

Data scanned: 0.00 MB

Data read: 1000.16 MB (ratio 0.00:1)

Time: 18.039 sec (0 m 18 s)

xdebcloud01-prod >> ~ :
```

**Comment by voroyam** [comment]
@VicDeo

**Comment by VicDeo** [comment]
@voroyam Note, that `scan-archive` is a CLI option. Using CLI mode is not recommended  as it is known to be slow and there is nothing we can do about it.

![Screenshot_20200731_111003](https://user-images.githubusercontent.com/991300/89014656-814ce000-d31e-11ea-889c-5fb34b6f7ced.png)

So my advice is to switch into socket/daemon mode and setup clamd accordingly:
```
ScanArchive BOOL
Enable archive scanning.
Default: yes
```
https://linux.die.net/man/5/clamd.conf

**Comment by voroyam** [comment]
So your advice is to simply add those 3 lines to the clams.conf while the app is in socket mode?

But with the Default set on yes, wouldn't it still scan the archives? This is what we want to avoid for the customer.

**Comment by VicDeo** [comment]
@voroyam 
> So your advice is to simply add those 3 lines to the clams.conf while the app is in socket mode?

nope, it is just an excerpt from `man clamd.conf`
my advice is to locate `ScanArchive` in `/etc/clamd.conf`, uncomment it,  set the value to `no`  and reload/restart clamd daemon

**Comment by voroyam** [comment]
Okay, this is something I can forward to the customer. Thank you :)

**Comment by voroyam** [comment]
@VicDeo what would be a good value for the max file size?

I think virus files are small files, so it would not be a good idea to scann a 750 GB upload, right?
