### ISSUE TITLE
Cron error: ArgumentCountError: Too few arguments to function

### ISSUE THREAD

**Issue by linkp** [owncloud/files_antivirus#378]
Installation Details
OS: Debian 10.5
OC: owncloud-files:all/unknown 10.5.0-1+2.1 uptodate
DB: mysql-community-server:amd64/buster 8.0.21-1debian10 uptodate
PHP: php7.4-fpm:amd64/buster 7.4.10-1+0~20200909.25+debian10~1.gbpe666e1 uptodate
APP: files_antivirus: 0.15.2

Since my upgrade from ownCloud 10.4 to 10.5 via the official Debian packages, the twice daily cron job that runs the Files_Antivirus has been consistently failing with the following output:

```
An unhandled exception has been thrown:
ArgumentCountError: Too few arguments to function OCA\Files_Antivirus\Cron\Task::run(), 0 passed in /var/www/owncloud/lib/private/BackgroundJob/Legacy/RegularJob.php on line 31 and exactly 1 expected in /var/www/owncloud/apps/files_antivirus/lib/Cron/Task.php:113
Stack trace:
#0 /var/www/owncloud/lib/private/BackgroundJob/Legacy/RegularJob.php(31): OCA\Files_Antivirus\Cron\Task::run()
#1 /var/www/owncloud/lib/private/BackgroundJob/Job.php(66): OC\BackgroundJob\Legacy\RegularJob->run()
#2 /var/www/owncloud/core/Command/System/Cron.php(125): OC\BackgroundJob\Job->execute()
#3 /var/www/owncloud/lib/composer/symfony/console/Command/Command.php(255): OC\Core\Command\System\Cron->execute()
#4 /var/www/owncloud/lib/composer/symfony/console/Application.php(1000): Symfony\Component\Console\Command\Command->run()
#5 /var/www/owncloud/lib/composer/symfony/console/Application.php(271): Symfony\Component\Console\Application->doRunCommand()
#6 /var/www/owncloud/lib/composer/symfony/console/Application.php(147): Symfony\Component\Console\Application->doRun()
#7 /var/www/owncloud/lib/private/Console/Application.php(165): Symfony\Component\Console\Application->run()
#8 /var/www/owncloud/console.php(116): OC\Console\Application->run()
#9 /var/www/owncloud/occ(11): require_once('/var/www/ownclo...')
#10 {main}
```

**Comment by phil-davis** [comment]
https://www.php.net/manual/en/migration71.incompatible.php

Since PHP 7.1 a problem like this has thrown an exception. (In PHP 7.0 and earlier there was only a warning, and the code went on)

I don't see where this code path has changed recently, so I am thinking that the issue has been there for some time.

@linkp what version of PHP were you using before upgrading?

What cron settings do you have?

**Comment by VicDeo** [comment]
strange. 
There are a lot of apps that should fail the same way: activity, market, files_versions, etc...

**Comment by linkp** [comment]
@phil-davis I was running ownCloud 10.4 on php 7.3 since it wasn't compatible with php 7.4. I switched to php 7.4 after upgrading to ownCloud 10.5. Both FPM & CLI PHP are on 7.4.

I run my cron from system cron every 15 minutes as the www-data user with the following:
` /usr/bin/chronic /usr/bin/php -f /var/www/owncloud/occ system:cron`
Chronic simply runs a command quietly unless it fails.

**Comment by dora71** [comment]
Are there any news about this bug? Is there a fix for it?
I also face the same problem.
I am using ownCloud 10.11.0.6 and App AntiVirus 1.1.0 together with ClamAV.
I am getting the above error message twice a day.

**Comment by DeepDiver1975** [comment]
@dora71 what php version? THX

**Comment by andreas69-by** [comment]
Are there any news about this bug? Is there a fix for it?
I also face the same problem.
I am using ownCloud 10.12.2.1 and App AntiVirus 1.2.2 together with ClamAV.
I am getting the above error message twice a day after switching to ownCloud 10.12.2.1. By switching to ownCloud 10.12.2.1 I was forced to run occ system:cron with php74. With ownCloud 10.11.0.6 it was allowed to run occ system:cron with php73.
I'm using PHP 7.4.30 (cli) (built: Oct  6 2022 15:27:18) on a Synology NAS with DSM 6.2.4

**Comment by CyberFred-CP** [comment]
This is still not fixed, despite further updates, since php 7.4 is mandatory, I'm still getting emails at regular inteval (likely when cron launches) :

```
An unhandled exception has been thrown:
ArgumentCountError: Too few arguments to function OCA\Files_Antivirus\Cron\Task::run(), 0 passed in /var/owncloud/lib/private/BackgroundJob/Legacy/RegularJob.php on line 31 and exactly 1 expected in /var/owncloud/apps-external/files_antivirus/lib/Cron/Task.php:113
Stack trace:
#0 /var/owncloud/lib/private/BackgroundJob/Legacy/RegularJob.php(31): OCA\Files_Antivirus\Cron\Task::run()
#1 /var/owncloud/lib/private/BackgroundJob/Job.php(81): OC\BackgroundJob\Legacy\RegularJob->run()
#2 /var/owncloud/core/Command/System/Cron.php(126): OC\BackgroundJob\Job->execute()
#3 /var/owncloud/lib/composer/symfony/console/Command/Command.php(298): OC\Core\Command\System\Cron->execute()
#4 /var/owncloud/lib/composer/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#5 /var/owncloud/lib/composer/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#6 /var/owncloud/lib/composer/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#7 /var/owncloud/lib/private/Console/Application.php(165): Symfony\Component\Console\Application->run()
#8 /var/owncloud/console.php(116): OC\Console\Application->run()
#9 /var/owncloud/occ(11): require_once('/var/owncloud/c...')
#10 {main}
```

**Comment by DeepDiver1975** [comment]
You can try to patch your installation with https://github.com/owncloud/files_antivirus/pull/554 and let us know if the issue has been fixed - THX

**Comment by CyberFred-CP** [comment]
> You can try to patch your installation with #554 and let us know if the issue has been fixed - THX

I may have missed something but :

An unhandled exception has been thrown:
Error: Using $this when not in object context in /var/owncloud/apps-external/files_antivirus/lib/Cron/Task.php:110
Stack trace:
#0 /var/owncloud/lib/private/BackgroundJob/Legacy/RegularJob.php(31): OCA\Files_Antivirus\Cron\Task::run()
#1 /var/owncloud/lib/private/BackgroundJob/Job.php(81): OC\BackgroundJob\Legacy\RegularJob->run()
#2 /var/owncloud/core/Command/System/Cron.php(126): OC\BackgroundJob\Job->execute()
#3 /var/owncloud/lib/composer/symfony/console/Command/Command.php(298): OC\Core\Command\System\Cron->execute()
#4 /var/owncloud/lib/composer/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#5 /var/owncloud/lib/composer/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#6 /var/owncloud/lib/composer/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#7 /var/owncloud/lib/private/Console/Application.php(165): Symfony\Component\Console\Application->run()
#8 /var/owncloud/console.php(116): OC\Console\Application->run()
#9 /var/owncloud/occ(11): require_once('/var/owncloud/c...')
#10 {main}

**Comment by CyberFred-CP** [comment]
> well - we got one step further ...... 🙈

Indeed...
