### ISSUE TITLE
[QA] eicar virus produces wrong error message

### ISSUE THREAD

**Issue by jnweiger** [owncloud/files_antivirus#395]
Seen with files_antivurus 0.16.0RC1 in oc-10.6.0:

![image](https://user-images.githubusercontent.com/1108546/106977093-ee23b580-6759-11eb-99ee-81ee221db680.png)
Permission to upload 'here' is the wrong reason. I have upload permission here. It fails due to a detected virus signature.

Expected behaviour: the message should say: "virus detected: eicar"

**Comment by jnweiger** [comment]
@VicDeo tracked that down to https://github.com/owncloud/core/blob/v10.4.1/apps/files/js/file-upload.js#L1205
I suggest to move the issue to core.

**Comment by VicDeo** [comment]
core regression for versions 10.4.1 - 10.6.0
fixed with https://github.com/owncloud/core/pull/38416
