### ISSUE TITLE
[QA] default mode 'executable' is slowest

### ISSUE THREAD

**Issue by jnweiger** [owncloud/files_antivirus#396]
Seen with files_antivirus 0.16.0RC1 in oc-10.6.0

Following the setup instructions in https://doc.owncloud.com/server/10.6/admin_manual/configuration/server/virus-scanner-support.html
The documentation discusses mode configuration.
For mode 'Executable' it warns:
"TIP
clamscan is slow and not always reliable for on-demand usage; it is better to use one of the daemon modes."

Nevertheless, the installation defaults to mode Executable.
The clamscan binary indeed takes ca 20 seconds on a small file and uses ca 1GB of RAM.
In daemon mode a small file is processed instantaneously.

Expected behaviour: Use mode "Daemon (socket)" mode per default.

**Comment by VicDeo** [comment]
@jnweiger the main idea behind this behavior is that `clamscan` is available in 99% of set ups while daemon/socket mode could be unavailable. So enabling the app makes the protection working right away.

There is a room for improvement definitely...
E.g. we can probe the socket/daemon defaults  () after the app is enabled  and use executable mode if the probe was unsuccessful

**Comment by VicDeo** [comment]
https://github.com/owncloud/files_antivirus/pull/399 introduces autoprobe when the app is enabled for the first time.
Now `executable`  is used by default only after both  daemon and socket mode are proved not to respond

**Comment by jnweiger** [comment]
Cool. That is good news.
We can accept a slow default for a while. Robustness is more important.

**Comment by jnweiger** [comment]
Confirmed fixed in 1.0.0-rc1
