### ISSUE TITLE
[QA] Documentation: log/delete choice

### ISSUE THREAD

**Issue by jnweiger** [owncloud/files_antivirus#397]
Seen with files_antivirus-0.16.0RC1 in oc-10.6.0

When a file contains the eicar virus signature it cannot be uploaded. (Permission denied error).
The admin configuration under security -> antiVirus allows no choice for this behaviour.

However the documentation explains:

----

#### What To Do With Infected Files Found During Scans

When infected files are detected during a scan, the app can take one of two actions:

*    Only log: Log the event.
*   Delete file: Delete the detected file.
----

This only applies to backgroud scans. The upload scan behaviour cannot be changed.

Expected behaviour: documentation matches implementation.

**Comment by VicDeo** [comment]
@jnweiger documentation:
https://doc.owncloud.com/server/10.6/admin_manual/configuration/server/virus-scanner-support.html#available-configuration-settings
> 
Setting | Description | Default
-- | -- | --
av_cmd_options | Extra command line options (comma-separated) to pass to ClamAV. |  
av_host | The hostname or IP address of the Antivirus server. |  
av_infected_action | The action to take when infected files were found during a **background scan**. It can be set to one of only_log and delete. | only_log
