### ISSUE TITLE
files_antivirus works without enterprise key

### ISSUE THREAD

**Issue by jnweiger** [owncloud/files_antivirus#40]
Do we consider files_antivirus an enterprise app? If so, it should check for auto-enabling the enterprise-key app. 

As seen in 8.0.3~RC4 testing, files_antivirus app can  be enabled, while the enterprise_key app remains disabled.

**Comment by LukasReschke** [comment]
files_antivirus is an opensource app.

**Comment by LukasReschke** [comment]
You can either look at the license or usually more reliable when doubt is to check whether  repository is public or private:

**Private:**
![2015-04-24_17-12-17](https://cloud.githubusercontent.com/assets/878997/7321919/20f221be-eaa5-11e4-95b0-a9d0c5422add.png)

**Public:**
![2015-04-24_17-12-12](https://cloud.githubusercontent.com/assets/878997/7321920/2216df9e-eaa5-11e4-9388-c28cd002bef0.png)

**Comment by jnweiger** [comment]
Right. On the other hand, I see it only in the enterprise tar balls and packages. Not in the communtiy releases.

**Comment by LukasReschke** [comment]
Yes. We don't ship it per default but it's anyways AGPL licensed for history reasons.
