### ISSUE TITLE
[QA] admin UI disappears when 'files-antivirus.scanner-class' is set

### ISSUE THREAD

**Issue by jnweiger** [owncloud/files_antivirus#400]
Tested with core 10.6.0, files_antivirus 0.16.0RC1, icap-1.0.0RC2

Normally, the owncloud admin user can configure files_antivirus via the security page:
![image](https://user-images.githubusercontent.com/1108546/107980458-9a6a6500-6fc0-11eb-8e5a-c6162066a65c.png)

----

As soon as icap and files_antivirus are connected via `occ config:system:set "files-antivirus.scanner-class" --value='OCA\ICAP\Scanner'`
This UI disppears: 

![image](https://user-images.githubusercontent.com/1108546/107980656-efa67680-6fc0-11eb-83de-2cb4d58c611f.png)

It can be restored by disconnecting icap via `occ config:system:delete "files-antivirus.scanner-class"`

Expected behaviour: the UI changes to show the config settings relevant for the new files-antivirus+icap combination.

**Comment by VicDeo** [comment]
This is how it was implemented by @DeepDiver1975  in https://github.com/owncloud/files_antivirus/pull/379

**Comment by jnweiger** [comment]
At least the "File size limit" is active when connected to icap. See https://github.com/owncloud/icap/issues/24

**Comment by DeepDiver1975** [comment]
this is done by intention.

icap config is set in config.php - web frontend has no capabilities to change config.php -> case closed ;-)

**Comment by jnweiger** [comment]
No. The file size limit from the gui is effective and the background scan setting is still effective.  see above.
Don't hide them!
Hide only the top part of the UI would be correct.

**Comment by DeepDiver1975** [comment]
not relevant anymore - icap app no longer exists
