### ISSUE TITLE
[QA] download from external storage is not scanned

### ISSUE THREAD

**Issue by jnweiger** [owncloud/files_antivirus#401]
Tested with core 10.6.0, files_antivirus 0.16.0RC1, icap-1.0.0RC2, kse-2.0.0.1157 via hetzner-deploy/setup_icap_kaspersky.sh
testpilotcloud-client 2.7.5 (build 3179)

* wget https://secure.eicar.com/eicar.com.txt ...
* Connect the ownloud server to an external storage. E.g. va SFTP and add some eicar test files into that storage:

```apt-get install pure-ftpd
adduser ftpdata
# password: ftpdata

# test the server
sftp ftpdata@localhost
sftp> mput eicar*
sftp> dir
 eicar.com             eicar.com.txt         eicar_com.zip         eicarcom2.zip
sftp> quit

# login to owncloud as admin
 -> Settings -> Storage
  SFTP, Username and password
  Configuration
        localhost       /home/ftpdata
        ftpdata         ftpdata
  All users.
```
* connect the client with user admin and wait for initial sync.
* a subfolder SFTP appears in the client sync folder root. It contains eicar test files. BAD.
* the client can rename the file, the renamed files propagate into the server. BAD.
* use `echo "    " >> eicar.com.txt` to append a few blanks to the downloaded eicar file.
* The client fails to upload, now the server recognizes the virus signature. OK.

Expected behavoiur: infected files from external storage should not be downloaded.

Workaround: Depending on the Files_Antivirus cron settings, such files may get removed after a while. (The default setting 'Log only' is sufficient to prevent uploads, but not downloads.)

**Comment by jnweiger** [comment]
* eicar.com.txt can be opened with the text editor in the Web UI. BAD.
* eicar.com can be downloaded from the Web UI. BAD.

**Comment by VicDeo** [comment]
it was agreed that we scan **on write**
scanning both on read and write will make the app superslow.

**Comment by VicDeo** [comment]
@jnweiger https://doc.owncloud.com/server/10.6/admin_manual/configuration/server/virus-scanner-support.html#things-to-note
>Files are checked when they are uploaded or updated (whether because they were edited or saved) but not when they are downloaded.

**Comment by jnweiger** [comment]
I wonder if there are any admins out there who'd favour an option "slow+safe" over "fast+spreading".

**Comment by VicDeo** [comment]
well, let those admin scan an external storage with any other tool **before** connecting it to owncloud ;)
we don't scan twice. wrapping `fwrite` operation does NOT allow to refer by file id which means that scanning both on read and on write means 'scanning twice'

**Comment by phil-davis** [comment]
IMO if you have a backend storage that you allow to be written to by somehow other than ownCloud, then that other "somehow" must also do anti-virus scan on write.

**Comment by jnweiger** [comment]
@pmaier1 is this input for docu, relnotes?

**Comment by micbar** [comment]
ok for me. Works as designed.
