### ISSUE TITLE
icap acceptance tests

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/files_antivirus#407]
Followup from https://github.com/owncloud/files_antivirus/pull/405

- [x] integrate icap into acceptance tests

**Comment by individual-it** [comment]
PR for running current acceptance tests with icap:  #409

we could add more tests, those things are also not tested with the old settings:
- UI tests for the settings
- behaviour on API / UI level if settings are set wrong / server dies

anything of that needed?

additionally we run all core tests with antivirus in the nightly builds, do we want to extend that to run them all also with icap?

**Comment by DeepDiver1975** [comment]
#409 is enough for me .... anything else to be decided by whoever is the overall qa responsible ....

**Comment by individual-it** [comment]
closing this issue, feel free to re-open if more tests are needed
