### ISSUE TITLE
[QA] Field validation passing Port number > 65535 on Antivirus Configuration screen

### ISSUE THREAD

**Issue by martjanoff** [owncloud/files_antivirus#422]
**Steps to reproduce:**
1. Log in as admin
2. Go to Settings -> Security
3. Mode - Daemon
4. Type in "81344" in Port field
5. Click on "Save" button

**Expected result:**
"Please match the requested format" info tip shown. Saving should not processed.
![2021-04-20_10-33-21](https://user-images.githubusercontent.com/37621174/115366712-3afe2080-a1ce-11eb-8180-d4933aaa1c01.png)

**Actual result:**
Changed have been successfully saved. "Test scan was unsuccessful. Please recheck antivirus settings." error message appears.
![image](https://user-images.githubusercontent.com/37621174/115366830-510be100-a1ce-11eb-8844-9c81c501f9cd.png)

**Comment by jnweiger** [comment]
Good spotting. Thanks. Adding that to the testplan!

**Comment by VicDeo** [comment]
@jnweiger I haven't found a release branch for 1.0.0
here is a fix against the master branch https://github.com/owncloud/files_antivirus/pull/423

**Comment by jnweiger** [comment]
Confirmed fixed in 1.0.0-rc2

(Now we have a release branch ...)
