### ISSUE TITLE
[QA] [Documentation and UX improvement] Users should be informed that in case saving empty values on Configuration screen uploading will be blocked

### ISSUE THREAD

**Issue by martjanoff** [owncloud/files_antivirus#425]
The UI should indicate that an incomplete config will block all uploads. 
The app should be either disabled or completely configured.

![Clipboard - April 20, 2021 3_05 PM](https://user-images.githubusercontent.com/37621174/115517880-4ca7fc80-a290-11eb-86cb-86dd403570bc.png)

**Comment by VicDeo** [comment]
> The UI should indicate that an incomplete config will block all uploads.

true

> The app should be either disabled or completely configured.

false :smirk:

**Comment by martjanoff** [comment]
@VicDeo got it)
btw, is it possible to contact you in https://talk.owncloud.com ?

**Comment by micbar** [comment]
Closed by improving configuration.
