### ISSUE TITLE
Keep users in mind

### ISSUE THREAD

**Issue by VicDeo** [owncloud/files_antivirus#429]
The error messaging  is too tech-savvy when the upload is broken due to unavailable antivirus . 
I think we need to expose 'File has been not uploaded because antivirus scanner is not reachable. Ask admin to validate files_antivirus configuration' to the end user and log the real reason with an `error` severity.

As for admin users - we still can show tech details to them.

**Comment by micbar** [comment]
Good idea! Accepted.

**Comment by jnweiger** [comment]
Confirmed fixed in 1.2.0-rc.1
