### ISSUE TITLE
ICAP-specific  settings should not be visible in other modes

### ISSUE THREAD

**Issue by VicDeo** [owncloud/files_antivirus#433]
![StaticShot_04-05-2021_15-48-54](https://user-images.githubusercontent.com/991300/117005885-72052380-acf0-11eb-8f14-5bf7e4ec0a26.png)

**Comment by VicDeo** [comment]
@jnweiger

**Comment by jnweiger** [comment]
Confirmed fixed in v1.0.0-rc2
