### ISSUE TITLE
[QA] deepdiver/icap-clamav-service:latest consumes multiple GB of RAM

### ISSUE THREAD

**Issue by jnweiger** [owncloud/files_antivirus#437]
Startup on a small CX11 Hetzner-Box fails:

```
Status: Downloaded newer image for deepdiver/icap-clamav-service:latest

LibClamAV Warning: **************************************************
LibClamAV Warning: ***  The virus database is older than 7 days!  ***
LibClamAV Warning: ***   Please update it as soon as possible.    ***
LibClamAV Warning: **************************************************
recomputing istag ...
recomputing istag ...
Child 8 did not exit normally.signaled with signal:9
/entrypoint.sh: line 2:     7 Killed                  /usr/bin/c-icap -f /etc/c-icap/c-icap.conf -D -N
```

With sufficient RAM, it works:

```
c-icap@8cf2318cb2ed:/$ ps auxww
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
c-icap         1  0.0  0.0  18380  2964 pts/0    Ss+  07:20   0:00 /bin/bash /entrypoint.sh
c-icap         6  4.1  7.3 1337404 1184372 pts/0 S+   07:20   0:19 /usr/bin/c-icap -f /etc/c-icap/c-icap.conf -D -N
c-icap         7  0.0  7.1 1427560 1153204 pts/0 Sl+  07:20   0:00 /usr/bin/c-icap -f /etc/c-icap/c-icap.conf -D -N
c-icap        19  0.0  7.1 1427560 1153204 pts/0 Sl+  07:20   0:00 /usr/bin/c-icap -f /etc/c-icap/c-icap.conf -D -N
```

Expected behaviour: It is a proxy service, it should not consume any noticeable RAM.

**Comment by phil-davis** [comment]
The nightly CI passed last night. That uses that icap docker image: https://drone.owncloud.com/owncloud/files_antivirus/1925/25/3
```
latest: Pulling from deepdiver/icap-clamav-service
Digest: sha256:efb1cc43b4fc239df3f79ff3be6987d6c0facb64a7d25d2ade9441c8db4d884b
Status: Downloaded newer image for deepdiver/icap-clamav-service:latest
```

**Comment by VicDeo** [comment]
I wonder is it really related to the app...

**Comment by jnweiger** [comment]
Not directly related to this app. Should we transfer the issue elsewhere?

**Comment by VicDeo** [comment]
@jnweiger slightly related: 
https://github.com/owncloud/files_antivirus/blob/b01b8691a5d5f5ef17bab33daa78b3ee18088c16/lib/Scanner/ICAPScanner.php#L32-L34

Such implementation will finally put the entire file content into RAM at the OC side. Which is basically a suboptimal approach.
`onAsyncData` method is supposed to send the data immediately instead of storing it.

**Comment by micbar** [comment]
@VicDeo Can we improve it?

**Comment by DeepDiver1975** [comment]
> `onAsyncData` method is supposed to send the data to the external scanner immediately instead of storing it.

- the icap protocol does not allow that afaik
- it is advised to define a max file size - it is pointless to send gb-sized files to any virus scanner
