### ISSUE TITLE
[QA] Error 500  "AV failed!" appears if to upload empty file using ICAP connected to Kaspersky Scan engine

### ISSUE THREAD

**Issue by martjanoff** [owncloud/files_antivirus#438]
**Pre-condition:**
ICAP connected to Kaspersky Scan engine is set up on machine.

**Steps to reproduce:**
- Log in as admin
- Go to /owncloud/index.php/apps/files
- Upload empty file ( tested with .txt, .zip, .doc)

**Expected result:**
Should be able to upload the file.

**Actual result:**
Error 500  "AV failed!" appears.

![image](https://user-images.githubusercontent.com/37621174/117992458-9fcd1680-b347-11eb-989f-1117e5541dc5.png)

**Comment by phil-davis** [comment]
I added this case to the automated tests - PR #439 
That is passing. The test suite uses `deepdiver/icap-clamav-service` as the ICAP service.

**Comment by VicDeo** [comment]
To be validated in the next Beta/RC

**Comment by jnweiger** [comment]
Confirmed fixed in v1.0.0-rc2
