### ISSUE TITLE
Acceptance tests failing in nightly CI

### ISSUE THREAD

**Issue by phil-davis** [owncloud/files_antivirus#463]
Various acceptance tests have been failing in nightly CI https://drone.owncloud.com/owncloud/files_antivirus/2114 since  2021-08-07 AM nightly run.

Needs investigation.

I will post a list of the failures...

**Comment by SwikritiT** [comment]
@phil-davis I have made these two issues with a list of failures
https://github.com/owncloud/files_antivirus/issues/461
https://github.com/owncloud/files_antivirus/issues/462

**Comment by phil-davis** [comment]
PR #464 was merged. CI is green again. 

core PR https://github.com/owncloud/core/pull/39168 is the change that really fixed it.
