### ISSUE TITLE
Not Checked. No matching rule for exit code -1. Please check antivirus rules configuration. File: 217Account: 057167C9-04F5-4F24-B825-0E5748DAFFA5 Path: /files_antivirus-stable8.zip

### ISSUE THREAD

**Issue by mesiah70** [owncloud/files_antivirus#47]
Hello,

what does that mean in my log? Not Checked. No matching rule for exit code -1. Please check antivirus rules configuration. File: 217Account: XXXXXXXXX   Path: /files_antivirus-stable8.zip

What I have to do to get clasmav working correctly without showing the error message above. Every time I upload a file, I got this error.

"Reset to defaults" didn't help

Thanks for your help

Mesiah

**Comment by DeepDiver1975** [comment]
@VicDeo please have a look - THX

**Comment by VicDeo** [comment]
@mesiah70 Do you have any rules in `advanced` section?

**Comment by VicDeo** [comment]
@mesiah70 ah, and according to your previous reports please let me know whether the table `oc_files_avir_status` exists in your database.

**Comment by mesiah70** [comment]
Yes, I do have rules, see below. I forgot to install clamav, now I've installed, not clamav Errors occured. How do I know, if the files are scanned? Further regarding  oc_files_avir_status   issue, I've removed the lines you've  showed and after that, all updates were through.


Scanner exit statuusScanner output 0  CleanInfectedUnchecked  
 Scanner exit statusScanner output 1  CleanInfectedUnchecked  
 Scanner exit statusScanner output 40 Unknown option passed. CleanInfectedUnchecked  
 Scanner exit statusScanner output 50 Database initialization error. CleanInfectedUnchecked  
 Scanner exit statusScanner output 52 Not supported file type. CleanInfectedUnchecked  
 Scanner exit statusScanner output 53 Can't open directory. CleanInfectedUnchecked  
 Scanner exit statusScanner output 54 Can't open file. (ofm) CleanInfectedUnchecked  
 Scanner exit statusScanner output 55 Error reading file. (ofm) CleanInfectedUnchecked  
 Scanner exit statusScanner output 56 Can't stat input file / directory. CleanInfectedUnchecked  
 Scanner exit statusScanner output 57 Can't get absolute path name of current working directory. CleanInfectedUnchecked  
 Scanner exit statusScanner output 58 I/O error, please check your file system. CleanInfectedUnchecked  
 Scanner exit statusScanner output 62 Can't initialize logger. CleanInfectedUnchecked  
 Scanner exit statusScanner output 63 Can't create temporary files/directories (check permissions). CleanInfectedUnchecked  
 Scanner exit statusScanner output 64 Can't write to temporary directory (please specify another one). CleanInfectedUnchecked  
 Scanner exit statusScanner output 70 Can't allocate memory (calloc). CleanInfectedUnchecked  
 Scanner exit statusScanner output 71 Can't allocate memory (malloc). CleanInfectedUnchecked  
 Scanner exit statusScanner output /.*: OK$/  CleanInfectedUnchecked  
 Scanner exit statusScanner output /.*: (.*) FOUND$/  CleanInfectedUnchecked  
 Scanner exit statusScanner output /.*: (.*) ERROR$/  CleanInfectedUnchecked

**Comment by VicDeo** [comment]
@mesiah70 so, it is gone after installing clamav?
Try uploading eicar http://www.eicar.org/86-0-Intended-use.html

**Comment by mesiah70** [comment]
Hello and sorry for replying so late. Yes indeed, I've uploaded (or tried) the eicar file, but clamav refused it to upload. So the clamav solution is working just fine.

1. Of course you must install the clamav first(this I forgot
2. You need to point to the correct clamav path
3. clamav has to run in daemon mode.

We can close this issue, thank you

**Comment by bcutter** [comment]
I also get this messages from time to time. Example (shortened):

`files_antivirus	Not Checked. No matching rules. Please check antivirus rules. ... filename.pdf`

ClamAV correctly set up, running as daemon (network socket). I use the standard rules and didn´t change them.

So what to do or check?

**Comment by VicDeo** [comment]
@bcutter could you please open a new issue with your OC version / app version and an exact log message?

**Comment by bcutter** [comment]
@VicDeo 
DONE (https://github.com/owncloud/files_antivirus/issues/166).
