### ISSUE TITLE
Encapsulated type count is wrong in ICAPClient

### ISSUE THREAD

**Issue by s-englert** [owncloud/files_antivirus#472]
In [ICAPClient.php](https://github.com/owncloud/files_antivirus/blob/master/lib/Scanner/ICAPScanner.php) the encapsulated count ist wrong.

The encapsulated type count is the sum from one step before. `$encapsulated[$type] = \strlen($bodyData);`

```php
$bodyData = '';
$hasBody = false;
$encapsulated = [];
foreach ($body as $type => $data) {
    switch ($type) {
        case 'req-hdr':
        case 'res-hdr':
            $encapsulated[$type] = \strlen($bodyData);
            $bodyData .= $data;
            break;

        case 'req-body':
        case 'res-body':
            $encapsulated[$type] = \strlen($bodyData);
            $bodyData .= \dechex(\strlen($data)) . "\r\n";
            $bodyData .= $data;
            $bodyData .= "\r\n";
            $hasBody = true;
            break;
    }
}
```
The right way should be **$data** in: 
```php 
$encapsulated[$type] = \strlen($data);
```

**Comment by jnweiger** [comment]
@s-englert do you have a patch for this?

**Comment by s-englert** [comment]
This is implemented in the [add-icap-scanners](https://github.com/owncloud/files_antivirus/tree/add-icap-scanners) branch.

**Comment by jnweiger** [comment]
This caused #491  - @jvillafanez reverted to correct behaviour in #495
