### ISSUE TITLE
ICAP Response Modification Mode is missing

### ISSUE THREAD

**Issue by s-englert** [owncloud/files_antivirus#473]
The response modification method is intended for post-processing performed on an HTTP response before it is delivered to a client. Examples include formatting HTML for display on special devices, human language translation, virus checking, and so forth.

[RFC 3507 Section 3.2](https://datatracker.ietf.org/doc/html/rfc3507#section-3.2)

**Comment by jnweiger** [comment]
@s-englert do you have a patch for this?

**Comment by s-englert** [comment]
The RESPMOD ist implemented in the [add-icap-scanners](https://github.com/owncloud/files_antivirus/tree/add-icap-scanners) branch.

**Comment by jnweiger** [comment]
Thanks. There is a list  of other updates, that also waits for a release. See https://github.com/owncloud/files_antivirus/issues/480#issue-1157417833

@s-englert Are they also in your add-icap-scanners branch?

**Comment by s-englert** [comment]
The #479 is not in the branch, the others all.

**Comment by jnweiger** [comment]
Thanks!
Later today, I'll base a 'release-1.1.0' branch on your add-icap-scanners branch, and build RC1 from there. Once the release is done, I'll merge back into master.

@s-englert alternatively you can also mere add-icap-scanners into master first. Both is fine with me.

**Comment by s-englert** [comment]
@jnweiger I think it's better, if you are on this. :-)

**Comment by jnweiger** [comment]
RC1 done. Ready for QA. https://github.com/owncloud/files_antivirus/releases/tag/v1.1.0-rc1

**Comment by jnweiger** [comment]
release done.
