### ISSUE TITLE
Advanced settings (list of rules) is not displayed

### ISSUE THREAD

**Issue by prsnbrg** [owncloud/files_antivirus#477]
When calling the rule list, the following entry is written to my log file:

`{"reqId":"Yh6J-z5sIGgAAGfwjegAAAAC","level":3,"time":"2022-03-01T22:02:55+01:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"mustermann","app":"index","method":"GET","url":"\/apps\/files_antivirus\/settings\/rule\/listall","message":"Exception: {\"Exception\":\"OCP\\\\AppFramework\\\\QueryException\",\"Message\":\"Could not resolve logger! Class logger does not exist or error resolving constructor arguments: Could not resolve RuleController! Class RuleController does not exist\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/vhosts\\\/DOMAIN\\\/cloud.DOMAIN\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main()\\n#1 \\\/var\\\/www\\\/vhosts\\\/DOMAIN\\\/cloud.DOMAIN\\\/lib\\\/private\\\/Route\\\/Router.php(344): OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke()\\n#2 \\\/var\\\/www\\\/vhosts\\\/DOMAIN\\\/cloud.DOMAIN\\\/lib\\\/base.php(927): OC\\\\Route\\\\Router->match()\\n#3 \\\/var\\\/www\\\/vhosts\\\/DOMAIN\\\/cloud.DOMAIN\\\/index.php(54): OC::handleRequest()\\n#4 {main}\",\"File\":\"\\\/var\\\/www\\\/vhosts\\\/DOMAIN\\\/cloud.DOMAIN\\\/lib\\\/private\\\/AppFramework\\\/App.php\",\"Line\":86}"}`

No rules are displayed in the list.
Even rules I added myself disappeared after a reloading the website.

oC version: 10.9.1
app version: 1.0.0

**Comment by phil-davis** [comment]
commit https://github.com/owncloud/files_antivirus/commit/a5dbd165a4efdff4d510d88de9b2dec5cd43af6e broke it.

before that commit, the Advanced list would open and display the entries. After that commit it stops working.

**Comment by jnweiger** [comment]
Confirmed fixed in 1.1.10-rc.2
