### ISSUE TITLE
Clean code ....

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/files_antivirus#48]
![bildschirmfoto von 2015-06-01 11 22 57](https://cloud.githubusercontent.com/assets/1005065/7909935/9fa7291e-0850-11e5-9e32-a7fb176021ea.png)

@VicDeo aren't you using PHPStorm? My eyes are bleeding if I see such code :wink:

**Comment by VicDeo** [comment]
@DeepDiver1975 
> aren't you using PHPStorm? 

I'm happy with Netbeans

**Comment by DeepDiver1975** [comment]
> I'm happy with Netbeans

I assume Netbeans also has nice colors? :wink:

**Comment by VicDeo** [comment]
@DeepDiver1975 sort of and it's  :free:

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 sort of and it's :free:

so - please - use the tools of choice and stop my eyes bleeding :wink:

**Comment by VicDeo** [comment]
@DeepDiver1975 Do you mean a yellow background areas? 
These pieces are not highlighted by Netbeans. 
Syntax analyzer is seems to be a property of Jetbrains :japanese_ogre:

**Comment by DeepDiver1975** [comment]
L29 - wrong var declaration (missing \)
Any various typos (fopen for sure not - but other green underlined areas)

**Comment by DeepDiver1975** [comment]
> These pieces are not highlighted by Netbeans.

Maybe not that great tool then ....

**Comment by VicDeo** [comment]
@DeepDiver1975 it's nothing but sugar nested in comments, not a real code.

**Comment by DeepDiver1975** [comment]
Issue has been addressed thx
