### ISSUE TITLE
Release files_antivirus 1.1.0

### ISSUE THREAD

**Issue by phil-davis** [owncloud/files_antivirus#480]
## Reason

- issue #477 PR #478 fixes the problem with Advanced rules not displaying in the UI
   - It was broken in v1.0.0-beta2 but not noticed - see my comments in issue #477 
- Issue #479 could also be looked into and fixed for a patch release. (And review other open issues)

- issue #472 @s-englert ??
- issue #473 @s-englert ??
- issue #488
- issue #489

Using issue template from /home/testy/src/github/owncloud/QA/tools/release/templates/server_app_release_template.md

### Product approval 

- [x] Verify transifex commits are in master: If a folder https://github.com/owncloud/<APPNAME>/tree/master/l10n exists, then https://drone.owncloud.com/owncloud/<APPNAME> should receive nightly '[tx] updated from transifex` ...
- [ ] Ping pmaier to check `info.xml` description and screenshot
- [ ] Get approval on translations from pmaier - send the date of the last tx commit from drone to Patrick

### QA

- [x] Create **QA** Milestone and set the description to $version
- [ ] Move tickets from milestone `development` to `qa` (testplan and tickets mentioned in release ticket)
- [x] Create release branch with the format "release-$version"
- [x] Create "$version Testplan" ([QA templates](https://github.com/owncloud/QA/tree/master/Server) or [Enterprise](https://github.com/owncloud/qa-enterprise/tree/master/Core)) -> #490 
- [x] copy new/reopened issues from the previous release ticket as 'Issues to review' below.
- [x] check if [Non-normal Release Process](https://confluence.owncloud.com/display/OG/Apps+with+special+release+process) applies, and adapt this checklist.

### Documentation

- [x] Changes in the docs needed? If so create issue in owncloud/docs-server. -> https://github.com/owncloud/docs-server/issues/471

### Marketing

- [ ] Ping @owncloud/marketing
- [x] Update https://confluence.owncloud.com/display/PROD/Upcoming+Releases
- [ ] Request a screenshot if the app is new or changed fundamentally

### Build

All actions to be done on the release branch from here:
- [x] Bump version in `info.xml` (no version suffix)
- [x] Bump "sonar.projectVersion=" in `sonar-project.properties` (no version suffix)
- [x] Check php version dependency in `info.xml`
- [x] Check minimum ownCloud version dependency in `info.xml`
- [x] Change CHANGELOG.md 'Unreleased' to '$version' (today's date)

#### Beta/RC

- [x] Ping product owner to create github tag for `v${version}-rc1` on release branch (see https://confluence.owncloud.com/display/EN/Product+Owners+List)
- [x] Build and sign RC tarball from github tag `v${version}-rc1` (see handbook for how to build)
- [x] Upload as Github release using changelog entries
- [x] Test and document in testplan + manual explorative testing:
    - [x] If this is an enterprise app: Enabling the app must start the grace period
    - [x] Add section "Changlog Testing" using github releases text or CHANGELOG.md from release branch
    - [x] Do changelog tests
    - [x] Do regression tests
    - [x] => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing issues in the "release-$version" branch

#### Final

- [x] Check that no documentation issues are pending
- [x] Rename last RC tarball to final
- [x] Create github tag for final `v${version}` on release branch
- [x] Upload as Github release using changelog entries

### Publishing

- [x] Upload tarball to marketplace (see handbook in confluence for details)
- [x] Publish tarball for customers  - [old 10](https://customer.owncloud.com/owncloud/index.php/apps/files/?dir=%2FownCloud-Enterprise%2FownCloud-10), [old 10.0](https://customer.owncloud.com/owncloud/index.php/apps/files/?dir=%2FownCloud-Server%2FownCloud-10.0) and [new portal](https://portal.owncloud.com/apps/files/?dir=/Portal%20Data/All%20Account%20Data/ownCloud%20Enterprise%20Resources%20Data/Server&fileid=5661) (see [handbook](https://confluence.owncloud.com/display/OG/Releasing+Apps) for details)
- [x] Send mail to release-coordination with link to this ticket and to the changelog
- [x] Copy email to rocket chat `#updates` channel

### Post-release

- [x] Add a new 'Unreleased' section in CHANGELOG.md (and also update links at the bottom!)
- [x] Create PR to merge changes back to the `master` branch with description "Closes #XYZ" with the release ticket number
- [x] Rename QA milestone to `$version` and close the milestone
- [x] Update https://confluence.owncloud.com/display/PROD/Upcoming+Releases
- [x] Ensure [release template](https://github.com/owncloud/QA/edit/master/tools/release/templates/server_app_release_template.md) is up to date
- [x] Ensure the testplan template ([community](https://github.com/owncloud/QA/tree/master/Server) or [enterprise](https://github.com/owncloud/qa-enterprise/tree/master/Core)) is up to date
- [x] Close the testplan issue

**Comment by pmaier1** [comment]
There's also another new feature pending for release. I'd keep this open for it. Is the version number 1.0.0 correct/intended? I think it should be 1.1.0 Changing.

**Comment by pmaier1** [comment]
cc @s-englert

**Comment by prsnbrg** [comment]
Is there a timetable for the release?

**Comment by jnweiger** [comment]
> Is there a timetable for the release?

Ah, sorry for the delay. We wanted to combine this with other features that are not yet ready. I'll check with engineering, how we can push forward best.

**Comment by jnweiger** [comment]
## Issues seen while testing
* [ ] https://github.com/owncloud/files_antivirus/issues/491

**Comment by jnweiger** [comment]
1.1.0 RC2 is ready for QA: https://github.com/owncloud/files_antivirus/releases/tag/v1.1.0-rc.2

**Comment by jnweiger** [comment]
Release is blocked by https://github.com/owncloud/files_antivirus/issues/491#issuecomment-1206707588

We need to add some logic. The current code can only support two out of three virus scanner backends either way.
Suggested fix: #500

**Comment by jnweiger** [comment]
RC3 passed QA with several defects. Most noticably #502

**Comment by jnweiger** [comment]
Release done, branch merged back to master.
