### ISSUE TITLE
[QA] Daemon and Executable mode are specific to ClamAV

### ISSUE THREAD

**Issue by jnweiger** [owncloud/files_antivirus#496]
Seen while testing files_antivirus 1.1.0 

The dropdown menu now names two more virus scanners: Fortinet and McAfeeWeb, while the original ClamAV remains unnamed:

![image](https://user-images.githubusercontent.com/1108546/182864831-d0beebc6-ac79-424e-b9b5-2008bf7ddd0d.png)

Expected behaviour:
* ClamAV Executable
* ClamAV Daemon
* ClamAV Daemon (Socket)
* ClamAV Daemon (ICAP)
* Fortinet (ICAP)
* McAfee Webgateway (ICAP)

**Comment by DeepDiver1975** [comment]
> * ClamAV Daemon (ICAP)

At least this one if wrong - ICAP is a generic implementation which can be used for different av products.
In the explicit case this is for clamav AND kaspersky.

Also the executable is designed to work with other command line scanners as well .... although I have never seen a different ...

**Comment by DeepDiver1975** [comment]
anyway -> close

**Comment by jnweiger** [comment]
Confirmed fixed in 1.2.0-rc.1
