### ISSUE TITLE
[QA] Fortinet (ICAP) backend somtimes fails to detect a zipped eicar test virus

### ISSUE THREAD

**Issue by jnweiger** [owncloud/files_antivirus#499]
Seen while testing files_antivirus 1.1.0

* Setup
   - ssh tunnel into VMLab to make 192.168.0.32:1344 appear as localhost:61344
   - Mode: Fortinet (ICAP)
   - Host: localhost
   - Port: 61344
   -  ICAP request service. Fortinet uses "respmod": respmod
   - ICAP response header. Fortinet sends X-Virus-ID: X-Virus-ID

Download eicar test signaturs from https://www.eicar.com/download-anti-malware-testfile/

* eicarcom.txt is detected, tried often. OK.
   - Even with additional text appended. (ClamAV would not detect that.) OK!
* eicarcom.zip is detected, tried often. OK.
* eicarcom2.zip is often detected. But on one occasion, it passed. BAD.

Not reproducable, sorry.

**Comment by DeepDiver1975** [comment]
> Not reproducable, sorry.

-> close
