### ISSUE TITLE
[QA] unclear icap behaviour without enterprise license

### ISSUE THREAD

**Issue by jnweiger** [owncloud/files_antivirus#530]
Seen with files_antivirus 1.2.1-rc.1 (probably not a regression)

* enable files_antivirus app
* a popup asks for an enterprise license. Add one.
* configure fortinet scanner via ICAP.
* the scanner works. OK
* go to the admin settings general interface and remove the enterprise license.
* the scanner still works. No grace period warning is shown. BAD.

Expected behaviour:
* ICAP requires an enterprise license
* The code seems to require an enterprise licenses, when using ICAP. See e.g. https://github.com/owncloud/files_antivirus/blob/master/lib/AppConfig.php#L189
* The docs seem to suggest that ICAP requires an enterprise license. https://doc.owncloud.com/server/10.11/admin_manual/configuration/server/virus-scanner-support.html#general-info

**Comment by jnweiger** [comment]
Same with camav icap without ever entering an enterprise license:
* a grace period popup is shown
![grafik](https://user-images.githubusercontent.com/1108546/203353185-9624eb3e-3bd9-4e4e-823a-a0e2bbdce6f6.png)
* the scanner works during the grace period. OK.

**Comment by jnweiger** [comment]
Without enterprice license and after the grace period is expired, the three different ICAP flavours behave as follows:

![grafik](https://user-images.githubusercontent.com/1108546/203368158-8325b63c-dfeb-4da2-9968-564885282f16.png)
* ClamAV and Kaspersky ICAP mode shows an error message: "No valid license found for icap scanner mode"

![grafik](https://user-images.githubusercontent.com/1108546/203368598-de7cd96b-71a8-4e69-8dea-3aa4154fa108.png)
* Fortinet ICAP mode just works. 

![grafik](https://user-images.githubusercontent.com/1108546/203369254-524e8a92-f10c-4adc-a961-a17ff51f0852.png)
McAfee + Skyhigh ICAP mode just works

**Comment by pako81** [comment]
the problem seems to be around https://github.com/owncloud/files_antivirus/blob/master/lib/AppConfig.php#L192 as the check is done against the icap class only.

Modifying it like:
```
if (
       $key === 'av_mode'
       && ($value === 'icap'|| $value === 'fortinet' || $value === 'mawgw')
       && !$this->licenseManager->checkLicenseFor($this->appName, ["disableApp" => false])
 )
```
will make the license check to take place for all three classes.

**Comment by pako81** [comment]
Proposed possible fix in https://github.com/owncloud/files_antivirus/pull/534
