### ISSUE TITLE
[QA] UI details about background scan should be hidden, when background scan is disabled

### ISSUE THREAD

**Issue by jnweiger** [owncloud/files_antivirus#531]
Seen with files_antivirus 1.2.1-rc.1 (probably not a regression)

* enable files_antivirus app
* visit admin general settings
* switch background scan from 'Enabled' to 'Disabled'
* The choice what to do with background scan results is still visible. BAD
![grafik](https://user-images.githubusercontent.com/1108546/203371196-9d33babd-13f2-435f-a39a-2bf784224c36.png)

Expected behaviour:
* as everything else in the antrivirus UI changes nicely according to context, this setting should do the same.

**Comment by jnweiger** [comment]
(Transifex now has Wirksache und Urkung in the right order: "Wenn infizierte Dateien bei einem Hintergrund-Scan gefunden werden", urks.)

**Comment by phil-davis** [comment]
- enable files_antivirus app
- visit admin security settings
- switch background scan from 'Enabled' to 'Disabled'

works in real-time.

But when I browse away from the page and come back to it, the details about background scan are displayed:

![Screenshot 2023-05-16 at 11-37-39 Settings - ownCloud](https://github.com/owncloud/files_antivirus/assets/1535615/022b7bed-8bc7-4a45-9879-4861e3d245ca)

There is still something needed to initialize the correct show/hide when the page is first rendered

**Comment by jnweiger** [comment]
Confirmed fixed in 1.2.2-rc.1
Thanks @prsnbrg !
