### ISSUE TITLE
drop running php tests with 7.3 

### ISSUE THREAD

**Issue by SwikritiT** [owncloud/files_antivirus#533]
In the recent nightly build the PHPUnit tests are failing with `7.3` with 
```
+ cd /var/www/owncloud/server
+ php occ a:l
This version of ownCloud requires at least PHP 7.4.0
You are currently running PHP 7.3.33-8+ubuntu18.04.1+deb.sury.org+1. Please update your PHP version.
```

since the minium version required for `oc10` is 7.4 maybe we can drop `7.3`

link to build: https://drone.owncloud.com/owncloud/files_antivirus/2790

**Comment by phil-davis** [comment]
done in #532 - maybe that was merged after the nightly CI started.

**Comment by SwikritiT** [comment]
> done in #532 - maybe that was merged after the nightly CI started.

Sorry didn't notice it!
