### ISSUE TITLE
App is marked as »Experimental«

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/files_antivirus#61]
![capture du 2015-07-08 11-40-34](https://cloud.githubusercontent.com/assets/925062/8567532/51b55bee-2566-11e5-8080-4bccced788c6.png)

Should most probably be »Official«. @DeepDiver1975 said this is defined via a json file in core. cc @VicDeo

**Comment by VicDeo** [comment]
@karlitschek is files_antivirus `experimental` or `official`? :unsure:

**Comment by karlitschek** [comment]
It should be official 
:-)

**Comment by VicDeo** [comment]
@DeepDiver1975 any reasons for removing `shipped` in https://github.com/owncloud/files_antivirus/commit/96f02016ab510b06b009c96c9bad3ba3289437af#diff-224bb875c5d3cfcd7621135069013242 ?

**Comment by karlitschek** [comment]
Well the problem is that it is part of the tar for EE but comes from the app store for community. That's the problem :-(

**Comment by DeepDiver1975** [comment]
The shipped flag in info.XML is no longer evaluate.
