### ISSUE TITLE
AntiVirus 0.7.0.1 crashes cron in OC 8.1?

### ISSUE THREAD

**Issue by TeZet2** [owncloud/files_antivirus#63]
Without activating Antivirus 0.7.0.1 cron works fine (OC 8.1). After activating app cron crashes with the following error:

PHP Fatal error: Call to a member function getUID() on a non-object in /var/www/owncloud/apps/files_antivirus/lib/backgroundscanner.php on line 94

This behavior is the same for running the app as deamon or as executeable. Deactivating app will result in a functioning cron again. clamd and freshclam -d are running.

**Comment by DeepDiver1975** [comment]
@TeZet2 which user backends are you using? How many users are on the backends? THX

**Comment by TeZet2** [comment]
Whooaaa, that's fast!!! I played around a little bit with LDAP but I am finished with that, LDAP has been deactivated again (but not sure if there are any permanent residues). What I am (successfully) using is OTP (multifactor authentication, OTP extension 2.5) but this is not active for all accounts (in fact it is not for the administrator account in order to have always a back door). Beside that I am running OC 8.1 out-of-the-box. Currently the OC installation is in a test phase so there are no more than 2 or 3 users online at the same time. The total number of users is 5 plus 3 additional users shared by email (accessing OC via link).

**Comment by DeepDiver1975** [comment]
> . What I am (successfully) using is OTP (multifactor authentication, OTP extension 2.5)

I have no idea how this app is implemented - but it might have a negative impact on the user manager search functionality.

**Comment by TeZet2** [comment]
I will give it a try (no problem at all as it is only running in a test environment for now). And since OC is running on ESXi I can simply do a snapshot and revert afterwards. As I am currently at work I need to go home first, so feedback will take two to three hours. Stay tuned ... ;-).

**Comment by TeZet2** [comment]
Bulls eye! I have deaktivated the OTP app and - voila - cron was fully functional with Antivirus 0.7.0.1 aktivated. After enabling OTP backend again cron crashed again. So seems to be some sort of incompatability. Any chance to fix this? Otherwise this is a decision between pest and cholera: Either sacrifice security during login or jeopardize the system by unrecognized viruses ... . Anyway, many thanks for pointing me in the right direction, I will be more sensitive according those issues in the future.

**Comment by DeepDiver1975** [comment]
I'd suggest to get in touch with the developer of the OTP app to get this fixed - you are for sure not the only user who might get affected

**Comment by TeZet2** [comment]
Will do. If no one mind I will keep this thread open for a few more days in case I get a feedback so all information will be in one place. If no new information turns up I will close this thread in about one week. Many thanks again.

**Comment by VicDeo** [comment]
https://github.com/owncloud/files_antivirus/blob/master/lib/backgroundscanner.php#L91
Should return an array of objects implementing \OCP\IUser interface. 
https://github.com/owncloud/core/blob/master/lib/public/iusermanager.php#L105
(or an empty array if there is no single user in this OC instance)

**Comment by VicDeo** [comment]
@TeZet2 any news from the OTP developer?
We merged https://github.com/owncloud/files_antivirus/pull/71 meanwhile. 
You are welcome to test it.

**Comment by TeZet2** [comment]
No news from OTP developer. My apologies for taking so long to test the changes. I replaced the "original" files by those listed above. I am impressed, the cron.php error is gone, no errors are shown in owncloud.log. What is not clear to me, does this fix mean that clamav is working or does it only suppress errors? Is there any chance to test anti-virus functionality (i.e. using EICAR)? Beside this question I really highly appreciate the help I got, thanks to all contributors. Please let me know if I can return the favor for example by further testing or anything else.

**Comment by VicDeo** [comment]
@TeZet2 
the app doesn't scan files in background now. Because we can't fix user retrieval we just check if any valid user is found.

But it still does scan files after uploading them.

**Comment by VicDeo** [comment]
@TeZet2 is the issue resolved for you?
