### ISSUE TITLE
Change recipient name in notification mail if using user_ldap

### ISSUE THREAD

**Issue by RostC** [owncloud/files_antivirus#66]
If I use files_antivirus and user_ldap app the recipient name in the notification mail is in standard config something like 
D14AB3F9-08F1-43AE-B83D-1D678A8A5416 <mail@myhost.com>

This is because the "username" in the database is  the AD objectGUID.
Would be great if in this case the displayname for example is the recipient name.

**Comment by karlitschek** [comment]
@VicDeo What do you think?
