### ISSUE TITLE
Infected file is moved only to trash if "delete file" is activated

### ISSUE THREAD

**Issue by michag86** [owncloud/files_antivirus#68]
### Steps to reproduce
1. Activate files_antivirus, configure and check that it is working
2. install/enable "Deleted files" app
3. set action for infected files to delete file
4. upload eicar test virus
5. go to deleted files
6. restore eicar test virus
7. now the virus can be downloaded or shared with other users

### Expected behaviour
infected file is deleted and not accessable by the user

### Actual behaviour
infected file is moved to deleted files and is restorable

### Server configuration
**Operating System:** CentOS 7.1
**Web server:** Apache 
**Database:** MariaDB
**PHP version:** 5.4.16
**ownCloud version:** 8.1
**Updated from an older ownCloud or fresh install:** fresh install

**other versions:** 
Antivirus App for files 0.7.0.1
Deleted files 0.6.3 
ClamAV 0.98.7

**Comment by karlitschek** [comment]
@VicDeo

**Comment by VicDeo** [comment]
hm. 
and how it is supposed to bypass `files_trashbin`? Kill it with fire before deleting an infected file?
