### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by ezraholm50** [owncloud/files_antivirus#70]
"reqId":"a8bf2ca524752014e6c8b7ff98cd","remoteAddr":"192.168.1.1","app":"PHP","message":"fwrite(): send of 1028 bytes failed with errno=32 Br"PUT","url":"\/remote.php\/webdav\/InstantUpload\/20150616_085350.mp4-chunking-7618-65-64"}$=32 Broken pipe at \/var\/www\/owncloud\/apps\/files_antivirus\/lib\/clamav.php#138","level":3,"time":"2015-06-16T06:54:43+00:00","method":"PUT",$

ubuntu 14.04
apache
owncloud 8.1.1

please help

**Comment by karlitschek** [comment]
@VicDeo can you have a look?

**Comment by VicDeo** [comment]
broken pipe means that connection was closed by other side (clamav)
there is no file `clamav.php` even for stable8 branch: https://github.com/owncloud/files_antivirus/tree/stable8/lib
Most likely your `files_antivirus` version is very very old.

**Comment by VicDeo** [comment]
Looks like that newer versions are also affected https://github.com/owncloud/files_antivirus/issues/69
Closing as a duplicate.
