### ISSUE TITLE
Installing commercial virus scanner in owncloud

### ISSUE THREAD

**Issue by cdamken** [owncloud/files_antivirus#72]
Customers keep asking me if they can user commercial virus scanner with owncloud.

We talk about clamav in our documentation: https://doc.owncloud.com/server/8.1/admin_manual/configuration_server/antivirus_configuration.html?highlight=antivirus#configuring-clamav-on-owncloud

But it suppose to run different antivirus too.

I asked in IRC without success. 

Could you provide me more information? and tell me if we already tested some other antivirus?

@MorrisJobke 

[00003488](https://na25.salesforce.com/500i000000Sy0tU?srPos=0&srKp=500)
[00003672](https://na25.salesforce.com/5003100000TqRWB?srPos=0&srKp=500)

**Comment by DeepDiver1975** [comment]
We tested no other solution \product.

@mtrichard pm call - thx

**Comment by cdamken** [comment]
@DeepDiver1975 Thanks

@MTRichards @bboule Is there any way we can test one or two?

**Comment by MTRichards** [comment]
Who did the initial development? I can't recall.

In theory it can, that was the development spec a long time ago, and how it was built, but needs testing. That is either a qa person or one of our gcx team.  Obviously.

**Comment by DeepDiver1975** [comment]
> Who did the initial development? I can't recall.

Initial by some external contributor - now @VicDeo is maintaining the app



> In theory it can, that was the development spec a long time ago, and how it was built, but needs testing.

Yes - within the app the admin can specify any other command line scanner.



> That is either a qa person or one of our gcx team. Obviously.

If we make this a qa task we should explicitly select one or two commercial scanners and state that we support them (once we know the integration works) and keep this as topic for the qa plan to retest these scanners on every release (major and maintenance.)

THX

**Comment by MTRichards** [comment]
Ok. So are you asking me which 2? @cdamken?

**Comment by cdamken** [comment]
@MTRichards Both customers asked about McAffee, that could be one of them.

I know that Kaspersky and Sophos are good too,

also there are free and paid versions like Avast, Bitdefender, AVG.

IMO McAffee (http://www.mcafee.com/us/products/virusscan-enterprise-for-linux.aspx) and Kaspersky (http://www.kaspersky.co.za/business-security/linux-file-server-antivirus) could be the options.

**Comment by MTRichards** [comment]
@DeepDiver1975 Agreed
It looks like McAfee at the top, then Kaspersky, Symantec and Trend Micro. Sophos a little further down.

Let's go with McAfee and Kaspersky for now. 

@cmonteroluque @DeepDiver1975 @karlitschek How do we add some time for antivirus testing to the queue?

Once we confirm this works, we can then adjust our documentation and marketing.
@carlaschroder FYI, when this is all tested we will need to document how to make the antivirus scan work with other scanner.

**Comment by DeepDiver1975** [comment]
> @cmonteroluque @DeepDiver1975 @karlitschek How do we add some time for antivirus testing to the queue?

Do we have the required licenses at hand?
How many licenses we need?
- x for devs
- x for qa
- x for documentation
- x for support
- x for gcx

**Comment by cdamken** [comment]
> Do we have the required licenses at hand?

@DeepDiver1975 There is a 30 days trial period in both antivirus

**Comment by MTRichards** [comment]
I am trying to get partner programs set up, but we may have to make do with the 30 day license.

**Comment by LukasReschke** [comment]
I'm pretty confident this is going in the wrong direction. Please take a look at ICAP and such stuff before going to do black magic using `exec`. :speak_no_evil:

**Comment by DeepDiver1975** [comment]
> Please take a look at ICAP

ICAP? please elaborate - THX

**Comment by MTRichards** [comment]
I think https://en.wikipedia.org/wiki/Internet_Content_Adaptation_Protocol

**Comment by cdamken** [comment]
>I am trying to get partner programs set up, but we may have to make do with the 30 day license.

@MTRichards  Did we got the partner program or we can test with a 30 day license?

@DeepDiver1975 Is there something I can help to testing it?

> I'm pretty confident this is going in the wrong direction. Please take a look at ICAP and such stuff before going to do black magic using exec. :speak_no_evil:4

@LukasReschke  Which direction should we go?

**Comment by LukasReschke** [comment]
Well. Whatever PM wants. I'm just saying that there are somewhat open standards that are somewhat working. Though they are more supported by the more enterprisy software products ;-)

**Comment by MTRichards** [comment]
No we did not get the partner program on any of it.
This will require developer time to test with a demo license to start. Honestly, the actual license is real short.

**Comment by cdamken** [comment]
@MTRichards That means for now we have an estimated time to deliver a solution?

**Comment by MTRichards** [comment]
No. Like I said, needs engineering time and none has been allocated.

-- 
Matt Richards
VP Products & Markets 
ownCloud, inc.

**Comment by cdamken** [comment]
@MTRichards How does it look now? Could I deliver some news to the customer?

**Comment by MTRichards** [comment]
Same story, sadly. Still. Needs engineering resources.

**Comment by MTRichards** [comment]
@cmonteroluque we full up for 9, right? Maybe I can tag as 9.0.

**Comment by cmonteroluque** [comment]
@MTRichards We are definitely full up for 9.0, and just the same, we can increase the priority on this if it's required. I don't think having a 30-day trial license is a great idea but if we're going to go that way then I would postpone this work until we've shipped 9.0.0 and then do the testing as part of the 9.0.1 work so we take advantage of the license right before we ship. If it's urgent (as in before April/May of 2016) then we need a plan B

**Comment by MTRichards** [comment]
Ok, I can live with that timeline. In the grander scheme this is not super urgent, but becomes a bit of a testing problem too. 
 I will tag 9.0.1.

**Comment by GitHubUser4234** [comment]
May I ask, will 9.0.1 only support ICAP for McAfee and Kaspersky? Or will Symantec be included also? Thanks.

**Comment by bboule** [comment]
@cdamken does this work?  Have you informed the user?

**Comment by MTRichards** [comment]
It is a matter of testing a setup. In theory it should work, but it needs testing.

@cmonteroluque I like the idea of using this for 9.0.1, testing post release of 9.0

**Comment by cdamken** [comment]
@bboule Yes, that will work and I did informed too

**Comment by cmonteroluque** [comment]
@rperezb @SergioBertolinSG @davitol @jvillafanez to add to work for 9.0.1

**Comment by CaptionF** [comment]
https://github.com/owncloud/enterprise/issues/1040

**Comment by felixboehm** [comment]
let me test integration of some alternatives

**Comment by felixboehm** [comment]
https://github.com/owncloud/enterprise/issues/1040#issuecomment-185651077

**Comment by felixboehm** [comment]
I could not get a response from Symantecs SAV as exit code or on stdout. Please let me know if s.o. uses this and knows more about this.

**Comment by carlaschroder** [comment]
Is this ready to document? I need access to a test system.

**Comment by felixboehm** [comment]
https://github.com/owncloud/enterprise/issues/1040#issuecomment-203395462

**Comment by PVince81** [comment]
Any update ? Is this still something we want soon or backlog ?

**Comment by settermjd** [comment]
Good question, where's this at? I've had a request from @felixboehm and @dercorn to add a section on virus scanners to the documentation. It'd be great to add a comprehensive section, detailing everything that is known and working.

**Comment by settermjd** [comment]
At this point, I've added a section to the documentation in 87b1c41bab72aca which mentions the core criteria for working with a virus scanner. However, given the incompleteness of the information available to hand, I've not specifically included any virus scanners, other than ClamAV.

**Comment by scorpaanon** [comment]
A good idea is to have the scanner work from start up incase recovery options are compromised.

**Comment by PVince81** [comment]
-> triage

also not sure how to track milestone as this is a purely documentation thing ?

**Comment by VicDeo** [comment]
@PVince81  IMO it needs to be paired and tested with at least one particular solution.
`other than ClamAV` is too generic.

a while ago I found nothing installable for my openSUSE that has a trial period.

**Comment by cdamken** [comment]
@pmaier1 @hodyroff this was asked for many customers before.

**Comment by hodyroff** [comment]
The only one we had success with was bitdefender. Otherwise ICAP is on our EE roadmap.

**Comment by micbar** [comment]
> Let's go with McAfee and Kaspersky for now.
Working as of v1.0.0
