### ISSUE TITLE
OC 8.2 support

### ISSUE THREAD

**Issue by ezraholm50** [owncloud/files_antivirus#89]
Could you update the owncloud appstore please?

**Comment by VicDeo** [comment]
@ezraholm50 published a minute ago.

**Comment by ezraholm50** [comment]
You're the best. Thanks for this great app!!!

Op zo 31 jan. 2016 11:44 schreef VicDeo <notifications@github.com>:

> @ezraholm50 <https://github.com/ezraholm50> published a minute ago.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/owncloud/files_antivirus/issues/89#issuecomment-177463354>
> .
>
-- 

Met vriendelijke groet,

E. Holm

**Comment by ezraholm50** [comment]
@VicDeo could you please update the appstore again for OC 9.0

**Comment by VicDeo** [comment]
@ezraholm50 Done

**Comment by ezraholm50** [comment]
Great thanks!

Op ma 14 mrt. 2016 23:50 schreef VicDeo <notifications@github.com>:

> @ezraholm50 <https://github.com/ezraholm50> Done
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/owncloud/files_antivirus/issues/89#issuecomment-196554170>
> .
>
-- 

Met vriendelijke groet,

E. Holm

**Comment by ezraholm50** [comment]
@VicDeo app hass no info.xml file. Activating it in the app store, problem
on my side?
Thanks

Op di 15 mrt. 2016 03:45 schreef Ezra Holm <ezraholm50@gmail.com>:

> Great thanks!
>
> Op ma 14 mrt. 2016 23:50 schreef VicDeo <notifications@github.com>:
>
>> @ezraholm50 <https://github.com/ezraholm50> Done
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/owncloud/files_antivirus/issues/89#issuecomment-196554170>
>> .
>>
> --
>
> Met vriendelijke groet,
>
> E. Holm
>
-- 

Met vriendelijke groet,

E. Holm

**Comment by ezraholm50** [comment]
Sorry can't edit the post on mobile, I can't test the github zip right now. Will test it later today or tomorrow, master and stable 9.0! You'll hear from me!

**Comment by VicDeo** [comment]
@ezraholm50 I published by compressing as `tar.bz2` (not intentionally)
Repacked with gzip and updated once more.

**Comment by ezraholm50** [comment]
Aah great will try asap! Also getting some errors about the app code,
possibly also related to the tar file? Will investigate some more and
report back!

Op di 15 mrt. 2016 15:22 schreef VicDeo <notifications@github.com>:

> @ezraholm50 <https://github.com/ezraholm50> I published by compressing as
> tar.bz2 (not intentionally)
> Repacked with gzip and updated once more.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
>
> https://github.com/owncloud/files_antivirus/issues/89#issuecomment-196843357
>
-- 

Met vriendelijke groet,

E. Holm
