### ISSUE TITLE
Is files_antivirus supposed to be in the apps folder?

### ISSUE THREAD

**Issue by jerrac** [owncloud/files_antivirus#9]
Specifically, I just downloaded the tar.gz for 7.0.4, and this app is not in the apps folder. Judging from the install instructions in the Readme.md, it seems like it should be... Should it?

If I install it manually, do I put http://github.com/kijin/simplesocket in the 3rdparty folder?

**Comment by DeepDiver1975** [comment]
@VicDeo can you please clarify this? THX - If this app has a 3rdparty dependency we should pull it in using composer - THX

**Comment by VicDeo** [comment]
I'm not aware of 3rdparty libraries and haven't seen its usage. Most likely readme is outdated.

**Comment by jerrac** [comment]
So, if I manually install this, I can just checkout the master branch,
stick it in apps, and it should be fine?

As for the subject of this issue,
http://doc.owncloud.org/server/7.0/admin_manual/configuration/antivirus_configuration.html
gives no indication that I should have to install files_antivirus
seperately from OwnCloud core. Yet, the 7.0.4 tarball does not contain
files_antivirus. It is supposed to?

--David Reagan

**Comment by VicDeo** [comment]
@jerrac this app is available for enabling from appstore even it is not bundled into the installation package:
 https://apps.owncloud.com/content/show.php/Antivirus?content=157439

But this requires working internet connection and `'appstoreenabled' => true,`  in `config.php`

**Comment by jerrac** [comment]
@VicDeo using the app store does not work in my deployment workflow. 

So, can you confirm that manual installation is just putting the files_antivirus folder in apps, then enabling the app via the admin ui?

The answer seems like an obvious "yes", but with the confusion over simplesocket, I want to confirm.

As for bundling, I'm just trying ot figure out if it is supposed to be bundled or not. If it isn't, then the docs I linked to need to be updated to let admins know they need to install it themselves. If it is, then core needs to add the app to the tarball when it is created.

**Comment by DeepDiver1975** [comment]
> If I install it manually, do I put http://github.com/kijin/simplesocket in the 3rdparty folder?

seems indeed to be outdated - please adjust @VicDeo THX

**Comment by DeepDiver1975** [comment]
> The answer seems like an obvious "yes", but with the confusion over simplesocket, I want to confirm.

yes :wink:
