### ISSUE TITLE
Antivirus app disappeared from app list in owncloud 9.0

### ISSUE THREAD

**Issue by arjanvs** [owncloud/files_antivirus#96]
Perhaps this is redundant with:
- https://github.com/owncloud/files_antivirus/issues/95

### Steps to reproduce
1. Install owncloud 9.0
2. Check webinterface apps

### Expected behaviour
Expected to see antivirus to link with clamav

### Actual behaviour
Nothing there, hence no virus protection

### Server configuration
GNU/linux Debian 8.0

According to documentation:
- https://doc.owncloud.org/server/9.0/admin_manual/configuration_server/antivirus_configuration.html

This should work.

Depending on the view of owncloud project concerning IT-security, the following solutions are possible:
- If antivirus is important, it would be benificial to fix the antivirus app
- If antivirus is not important, delete the part about antivirus in the documentation

See also: https://github.com/owncloud/core/issues/23242#issuecomment-196499826

**Comment by VicDeo** [comment]
Published
https://apps.owncloud.com/content/show.php/Antivirus?content=157439
https://github.com/owncloud/files_antivirus/releases/tag/stable9-0.8.0.1

**Comment by carlaschroder** [comment]
Hi, I could use a little help here. How is this supposed to work? The app is updated in the app store, but my oC 9 still complains about the code integrity check failure. Also, it keeps complaining even when I disable the app. Which was never downloaded because it failed the code integrity check :)

**Comment by VicDeo** [comment]
@carlaschroder and how it is related with `Antivirus app disappeared from app list in owncloud 9.0`? :)
I bet #95 is more relevant.

**Comment by VicDeo** [comment]
@carlaschroder  >it keeps complaining even when I disable the app.

I suspect it to be a pure caching issue, should be filed against the core

**Comment by carlaschroder** [comment]
My  mistake, the integrity check is reporting .htaccess. Thanks @VicDeo 

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- INVALID_HASH
		- .htaccess

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [.htaccess] => Array
                        (
                            [expected] => f40e7ca19cd76ff922ccd164e38f4d73806f66170cafa202fb470be225c813b4b242f4321da8a01bef1329e300acf3d137dbcbff058c501f166a2619031fc651
                            [current] => 97ef2d101ed21e46bcd19fd62682d559ec5210e0ade76eff961f7a33b260016addcc2463d6772f540f2b51379696d170f09f6f24626306ac1a4c1922f3f33de7
                        )

                )

        )

)
```

**Comment by arjanvs** [comment]
It is back, thx for fixing
